from turtle import *

def ici(taille,grosseur):
    

    t=taille
    g=grosseur

    tracer(0)

    up()
    backward(t*55)
    right(90)
    forward(t*112)
    left(110)
    down()

    #T-Shirt et cercle du logo
    begin_fill()
    forward(t*30)
    right(110)
    circle(t*25,160)
    right(90)
    forward(t*27)
    right(120)
    width(g*3)
    circle(t*-78,85)
    end_fill()
    circle(t*-78,275)

    pencolor('blue')
    width(g*1)
    right(65)
    forward(t*27)
    left(100)
    circle(t*-25,160)
    left(100)
    forward(t*30)
    backward(t*30)
    
    #Visage du logo
    fillcolor('red')
    begin_fill()
    right(135)
    circle(t*35,60)
    left(70)
    circle(t*-5,90)
    forward(t*15)
    circle(t*-2,180)
    forward(t*5)
    right(195)
    forward(t*20)
    right(30)
    forward(t*23)
    right(55)
    forward(t*30)
    right(55)
    forward(t*23)
    right(30)
    forward(t*21)
    left(160)
    forward(t*7)
    circle(t*-2.5,180)
    forward(t*17)
    circle(t*-5,90)
    left(70)
    circle(t*35,65)
    right(42)
    circle(t*-25,160)
    end_fill()
    
    up()
    forward(t*55)
    right(90)
    forward(t*5)
    left(85)
    down()

    #Cheveux
    fillcolor('blue')
    begin_fill()
    circle(t*-50,45)
    right(60)
    circle(t*100,17)
    right(50)
    circle(t*-50,45)
    left(140)
    circle(t*35,90)
    circle(t*-20,20)
    circle(t*20,20)
    left(20)
    circle(t*40,140)
    end_fill()

    #Masque
    left(60)
    up()
    forward(t*10)
    down()
    begin_fill()
    left(15)
    circle(t*-80,35)
    right(80)
    forward(t*25)
    circle(t*-22,150)
    right(20)
    forward(t*28)
    end_fill()
    
    up()
    forward(t*120)
    left(90)
    forward(t*145)
    right(90)
    write("EST OBLIGATOIRE", font=("Arial", int(28*t), "normal"))
    backward(t*5)
    right(90)
    down()
    width(g*4)
    forward(t*215)
    right(110)
    forward(t*30)
    left(150)
    forward(t*40)
    right(40)
    forward(t*80)

    up()
    backward(t*290)
    left(90)
    forward(t*60)
    down()
    width(g*1)
    write("ICI,LE MASQUE", font=("Arial", int(28*t), "normal"))

    up()
    forward(t*60)
    right(90)
    forward(t*86)
    down()

    fillcolor('black')
    begin_fill()
    for i in range(2):
        forward(t*110)
        left(90)
        forward(t*35)
        left(90)
    end_fill()

    up()
    forward(t*20)
    left(90)
    forward(t*5)
    down()
    pencolor('white')
    write("COVID-19", font=("Arial", int(13*t), "bold"))
    
    up()
    backward(t*370)
    right(90)
    backward(t*15)
    pencolor('blue')
    write("Ensemble,", font=("Arial", int(16*t), "normal"))

    backward(t*110)
    right(90)
    forward(t*25)
    write("faisons bloc contre le coronavirus", font=("Arial", int(16*t), "normal"))

    forward(t*40)
    left(90)
    backward(t*95)
    down()

    width(g*3)

    for i in range(2):
        forward(t*510)
        left(90)
        forward(t*500)
        left(90)
    
    
    update()

