from turtle import *
from setup import *

def chat(ecran,taille,x,y,angle=0):

    tortuechat=Turtle(undobuffersize=0,visible=False,shape="square")
    chat = Shape("compound")
    setup(x,y,angle,tortuechat)

    t=taille/11

    tracer(0)
    tortuechat.begin_poly()
    tortuechat.up()
    tortuechat.forward(t*20)
    tortuechat.right(90)
    tortuechat.forward(t*34)
    tortuechat.left(90)
    
    #tortuechat.down()

    tortuechat.width(4*t)
    tortuechat.pencolor('black')
    tortuechat.fillcolor('white')

    #Pelage ventre du chat
    tortuechat.begin_poly()
    tortuechat.circle(t*1600,6.7)
    tortuechat.right(110)
    tortuechat.circle(t*100,29)
    tortuechat.right(90)
    tortuechat.circle(t*-320,35.5)
    tortuechat.right(97)
    tortuechat.circle(t*60,33)
    tortuechat.end_poly()
    chat.addcomponent(tortuechat.get_poly(), "white", "black")
    #Je colorie tout le corps du chat en orange
    tortuechat.fillcolor('#db6927')
    tortuechat.begin_poly()
    tortuechat.right(180)
    tortuechat.circle(t*-55,37)
    tortuechat.right(28)
    tortuechat.forward(t*150)
    tortuechat.left(70)
    tortuechat.circle(t*-99,48)
    tortuechat.right(10)
    tortuechat.circle(t*-35,70)
    tortuechat.circle(t*-23,130)
    tortuechat.left(180)
    tortuechat.circle(t*23,105)
    tortuechat.right(85)
    tortuechat.circle(t*-23,140)
    tortuechat.circle(t*-60,25)
    tortuechat.left(180)
    tortuechat.circle(t*60,25)
    tortuechat.circle(t*23,17)
    tortuechat.right(100)
    tortuechat.circle(t*-25,60)
    tortuechat.right(20)
    tortuechat.circle(t*-55,50)
    tortuechat.right(3)
    tortuechat.circle(t*-550,15)
    tortuechat.forward(t*112)
    tortuechat.forward(t*-46)
    tortuechat.left(114)
    tortuechat.circle(t*-300,8.5)
    tortuechat.left(70)
    tortuechat.circle(t*-290,50)
    tortuechat.circle(t*-80,113)
    tortuechat.circle(t*-290,43.5)
    tortuechat.left(43)
    tortuechat.forward(t*123)
    tortuechat.right(152.5)
    tortuechat.forward(t*130)
    tortuechat.left(133)
    tortuechat.circle(t*-90,35)
    w,x=tortuechat.pos()

    tortuechat.up()
    tortuechat.goto(w,x)

    tortuechat.circle(t*-99,23)
    #tortuechat.down()

    tortuechat.circle(t*-60,90)
    tortuechat.left(3)
    tortuechat.circle(t*-190,34)
    tortuechat.right(180)
    tortuechat.circle(t*190,31)
    tortuechat.right(39)
    tortuechat.forward(t*230)
    tortuechat.circle(t*-90,25)
    tortuechat.left(70)
    tortuechat.forward(t*200)
    tortuechat.right(2)
    tortuechat.circle(t*-200,20)
    tortuechat.circle(t*-150,70)
    tortuechat.circle(t*-30,170)
    tortuechat.circle(t*100,68)
    tortuechat.circle(t*300,10)
    tortuechat.forward(t*175)
    tortuechat.left(70)
    tortuechat.circle(t*-100,40)
    tortuechat.right(5.9)
    tortuechat.circle(t*-500,7)
    tortuechat.circle(t*2,120)
    tortuechat.circle(t*300,8.5)
    tortuechat.circle(t*-10,40)
    tortuechat.circle(t*-40,67)
    tortuechat.left(10)
    tortuechat.circle(t*-150,73)
    tortuechat.left(1)
    tortuechat.circle(t*-40,61)
    tortuechat.left(30)
    tortuechat.forward(t*10)
    tortuechat.right(30)
    tortuechat.circle(t*-22,160)
    tortuechat.left(20)
    tortuechat.forward(t*10)
    tortuechat.forward(t*-10)
    tortuechat.right(20)
    tortuechat.left(180)
    tortuechat.circle(t*22,125)
    tortuechat.right(100)
    tortuechat.circle(t*-22,150)
    tortuechat.circle(t*-32,50)
    tortuechat.left(180)
    tortuechat.circle(t*32,50)
    tortuechat.circle(t*22,59)
    tortuechat.right(100)
    tortuechat.circle(t*-20,150)
    tortuechat.left(5)
    tortuechat.circle(t*-100,40)
    tortuechat.left(60)
    tortuechat.forward(t*38)
    tortuechat.left(150)
    tortuechat.circle(t*-76,60)
    tortuechat.right(22)
    tortuechat.circle(t*-70,70)
    tortuechat.left(10)
    tortuechat.circle(t*-100,17)
    tortuechat.left(180)
    tortuechat.circle(t*100,17)
    tortuechat.right(10)
    tortuechat.circle(t*70,15)
    tortuechat.right(70)
    tortuechat.circle(t*-1600,6.7) 
    tortuechat.end_poly()
    chat.addcomponent(tortuechat.get_poly(), '#db6927', "black")
    tortuechat.up()
    tortuechat.left(95)
    tortuechat.circle(t*-60,33)
    #tortuechat.down()

    #Je fais les pattes arrières séparemment car m'évite un déplacement inutile
    tortuechat.begin_poly()
    tortuechat.left(99)
    tortuechat.circle(t*320,10)
    tortuechat.right(53)
    tortuechat.circle(t*200,18)
    tortuechat.left(65)
    tortuechat.forward(t*40)
    tortuechat.left(140)
    tortuechat.circle(t*-25,83)
    tortuechat.right(75)
    tortuechat.circle(t*320,15)
    tortuechat.right(150)
    tortuechat.circle(t*30,70)
    tortuechat.left(68)
    tortuechat.circle(t*-30,80)
    tortuechat.right(80)
    tortuechat.circle(t*46,56)
    tortuechat.right(53)
    tortuechat.circle(t*-230,31)
    tortuechat.right(140)
    tortuechat.circle(t*50,82)
    tortuechat.left(180)
    tortuechat.circle(t*-50,102)
    tortuechat.left(5)
    tortuechat.circle(t*-280,10)
    tortuechat.circle(t*-70,45)
    tortuechat.right(35)
    tortuechat.circle(t*-22,110)
    tortuechat.left(180)
    tortuechat.circle(t*22,110)
    tortuechat.right(80)
    tortuechat.circle(t*-23,220)
    tortuechat.left(180)
    tortuechat.circle(t*23,100)
    tortuechat.right(80)
    tortuechat.circle(t*-10,100)
    tortuechat.circle(t*-30,75)
    tortuechat.left(6)
    tortuechat.circle(t*-300,15)
    tortuechat.left(115)
    tortuechat.forward(t*54)
    tortuechat.right(90)
    tortuechat.forward(t*25)
    tortuechat.end_poly()
    chat.addcomponent(tortuechat.get_poly(), '#db6927', "black")


    tortuechat.up()
    tortuechat.backward(t*150)
    tortuechat.left(90)
    tortuechat.forward(t*150)
    tortuechat.right(120)
    #tortuechat.down()

    #Je fais le museau en blanc
    tortuechat.fillcolor('white')
    tortuechat.begin_poly()
    tortuechat.circle(t*100,40)
    tortuechat.left(5)
    tortuechat.circle(t*30,90)
    tortuechat.left(4)
    tortuechat.circle(t*230,40)
    tortuechat.up()
    tortuechat.circle(t*230,18)
    #tortuechat.down()
    tortuechat.circle(t*230,10)
    tortuechat.left(55)
    tortuechat.circle(t*60,60)
    tortuechat.circle(t*220,50)
    tortuechat.end_poly()
    chat.addcomponent(tortuechat.get_poly(), "white", "black")

    tortuechat.up()
    tortuechat.forward(t*-14)
    tortuechat.left(90)
    tortuechat.forward(t*120)
    #tortuechat.down()
    
    #Le blanc des yeux
    tortuechat.begin_poly()
    tortuechat.right(110)
    tortuechat.circle(t*34,91)
    l,m=tortuechat.pos()
    tortuechat.left(93)
    tortuechat.forward(t*85)
    tortuechat.up()
    tortuechat.forward(t*10)
    tortuechat.left(90)
    tortuechat.forward(t*-3)
    tortuechat.right(90)
    #tortuechat.down()
    tortuechat.circle(t*400,7.5)
    tortuechat.left(50)
    tortuechat.circle(t*30,47)
    i,o=tortuechat.pos()
    tortuechat.left(85)
    tortuechat.up()
    tortuechat.circle(t*-100,30)
    #tortuechat.down()
    tortuechat.left(25)
    tortuechat.circle(t*-290,15)
    tortuechat.end_poly()
    chat.addcomponent(tortuechat.get_poly(), "white", "black")

    #Le nez du chat
    tortuechat.up()
    tortuechat.goto(i,o)
    #tortuechat.down()
    tortuechat.right(65)
    tortuechat.fillcolor('#3784a9')
    tortuechat.begin_poly()
    tortuechat.right(100)
    tortuechat.circle(t*15,110)
    tortuechat.left(40)
    tortuechat.circle(t*170,13)
    tortuechat.left(70)
    tortuechat.circle(t*-70,35)
    tortuechat.left(140)
    tortuechat.circle(t*130,30)
    tortuechat.end_poly()
    chat.addcomponent(tortuechat.get_poly(), '#3784a9', "black")
    #La bouche
    tortuechat.up()
    tortuechat.left(120)
    tortuechat.forward(t*50)
    #tortuechat.down()
    tortuechat.begin_poly()

    tortuechat.right(20)
    tortuechat.circle(t*70,20)
    tortuechat.left(60)
    tortuechat.forward(t*-20)
    tortuechat.forward(t*20)
    tortuechat.circle(t*-100,44)
    tortuechat.end_poly()
    chat.addcomponent(tortuechat.get_poly(), 'black', "black")
    #Les moustaches
    tortuechat.up()
    tortuechat.circle(t*60,35)
    #tortuechat.down()
    tortuechat.left(6)
    tortuechat.circle(t*-260,33)

    tortuechat.up()
    tortuechat.left(180)
    tortuechat.circle(t*260,30)
    tortuechat.left(90)
    tortuechat.forward(t*-20)
    tortuechat.left(97)
    #tortuechat.down()
    tortuechat.circle(t*-200,30)

    tortuechat.up()
    tortuechat.left(180)
    tortuechat.circle(t*200,37)
    tortuechat.right(90)
    tortuechat.forward(t*25)
    #tortuechat.down()
    tortuechat.right(87)
    tortuechat.circle(t*-200,40)

    tortuechat.up()
    tortuechat.backward(t*280)
    tortuechat.right(90)
    tortuechat.forward(t*120)
    #tortuechat.down()

    tortuechat.right(55)
    tortuechat.circle(t*130,30)


    tortuechat.up()
    tortuechat.left(180)
    tortuechat.circle(t*-130,30)
    tortuechat.left(90)
    tortuechat.forward(t*20)
    #tortuechat.down()

    tortuechat.left(75)
    tortuechat.circle(t*150,45)

    tortuechat.up()
    tortuechat.left(180)
    tortuechat.circle(t*-150,45)
    tortuechat.left(90)
    tortuechat.forward(t*20)
    #tortuechat.down()

    tortuechat.left(75)
    tortuechat.circle(t*150,40)

    #Le contour des yeux et les sourcils
    tortuechat.up()
    tortuechat.goto(l,m)
    #tortuechat.down()
    tortuechat.right(117)
    tortuechat.circle(t*34,110)
    tortuechat.left(15)
    tortuechat.up()
    tortuechat.forward(t*50)
    #tortuechat.down()
    tortuechat.left(185)
    tortuechat.circle(t*-400,16)
    tortuechat.right(60)
    tortuechat.circle(t*-40,60)

    tortuechat.up()
    tortuechat.right(73)
    tortuechat.forward(t*112)
    #tortuechat.down()
    tortuechat.right(125)
    tortuechat.circle(t*-200,17)

    tortuechat.left(155)
    tortuechat.up()
    tortuechat.forward(t*27)
    #tortuechat.down()
    tortuechat.left(20)
    tortuechat.circle(t*50,47)
    tortuechat.right(127)
    tortuechat.circle(t*-60,40)
    tortuechat.left(90)
    tortuechat.circle(t*30,35)

    tortuechat.up()
    tortuechat.left(180)
    tortuechat.circle(t*-30,35)
    tortuechat.right(90)
    tortuechat.circle(t*60,17)
    tortuechat.right(120)
    #tortuechat.down()
    tortuechat.circle(t*45,50)

    tortuechat.up()
    tortuechat.right(104)
    tortuechat.forward(t*24)
    tortuechat.right(90)
    tortuechat.fillcolor('#db6927')
    tortuechat.begin_poly()
    tortuechat.circle(t*-300,23)
    #tortuechat.down()

    #Oreille droite de l'animal
    tortuechat.left(115)
    tortuechat.circle(t*-300,16.5)
    tortuechat.left(120)
    tortuechat.circle(t*300,11.5)
    tortuechat.left(150)
    tortuechat.circle(t*-10,130)
    tortuechat.circle(t*-30,90)
    tortuechat.left(70)
    tortuechat.circle(t*300,8.5)
    tortuechat.end_poly()
    chat.addcomponent(tortuechat.get_poly(), '#db6927', "black")


    #Les deux yeux  
    tortuechat.up()
    tortuechat.left(70)
    tortuechat.fillcolor('black')
    tortuechat.begin_poly()
    tortuechat.forward(t*42)
    #tortuechat.down()
    tortuechat.right(100)
    tortuechat.circle(t*7,360)
    tortuechat.end_poly()
    chat.addcomponent(tortuechat.get_poly(), "black", 'black')

    tortuechat.up()
    tortuechat.left(125)
    tortuechat.forward(t*60)
    #tortuechat.down()
    tortuechat.begin_poly()
    tortuechat.circle(t*7,360)
    tortuechat.end_poly()
    chat.addcomponent(tortuechat.get_poly(), "black", 'black')

    #L'oreille gauche
    tortuechat.up()
    tortuechat.goto(w,x)
    tortuechat.fillcolor('#f2b3a3')
    tortuechat.begin_poly()
    tortuechat.left(180)
    tortuechat.circle(t*100,28)
    tortuechat.left(180)
    tortuechat.circle(t*-100,49)
    tortuechat.left(135)
    #tortuechat.down()
    tortuechat.circle(t*700,12)
    tortuechat.left(137.5)
    tortuechat.forward(t*137)
    tortuechat.left(133)
    tortuechat.up()
    tortuechat.circle(t*-100,25)
    tortuechat.end_poly()
    chat.addcomponent(tortuechat.get_poly(), '#f2b3a3', "black")

    tortuechat.goto(w,x)
    tortuechat.left(525)
    #tortuechat.down()

    #Les finitions en dessous de l'oreille
    tortuechat.left(20)
    tortuechat.circle(t*90,28)
    tortuechat.right(195)
    tortuechat.circle(t*-60,45)
    tortuechat.right(140)
    tortuechat.circle(t*60,25)
    tortuechat.left(150)
    tortuechat.circle(t*-40,40)
    tortuechat.left(220)
    tortuechat.circle(t*30,30)
    ecran.addshape('chat', shape=chat)
    update()


testscreen=Screen()
chat(testscreen,11,0,0)
tu=Turtle(shape="chat")
while True:
    tu.left(1)
    update()

update()
input()