from setup import *
def pate(taille,x,y,angle=0):
    x+=5*taille
    tortuepate=Turtle(undobuffersize=0,visible=False,shape="square")
    setup(x,y,angle,tortuepate)

    t=taille/6

    tracer(0)

    width(4*t)
    tortuepate.pencolor('black')

    #Fermeture du paquet
    tortuepate.fillcolor('#e2261a')
    tortuepate.begin_fill()
    tortuepate.up()
    tortuepate.forward(t*15)
    tortuepate.left(90)
    tortuepate.forward(t*125)
    tortuepate.down()

    tortuepate.forward(t*20)
    tortuepate.right(20)
    tortuepate.forward(t*20)
    tortuepate.left(20)
    tortuepate.circle(t*12,100)
    g,h=tortuepate.pos()
    tortuepate.left(50)
    tortuepate.forward(t*25)
    tortuepate.circle(t*6,180)
    tortuepate.up()
    tortuepate.goto(g,h)
    tortuepate.down()
    tortuepate.left(40)
    tortuepate.circle(t*-15,70)
    tortuepate.left(152)
    tortuepate.circle(t*700,10)
    tortuepate.circle(t*-200,17)
    tortuepate.circle(t*10,70)
    tortuepate.forward(t*30)
    y,u=tortuepate.pos()
    tortuepate.circle(t*8,120)
    tortuepate.up()
    tortuepate.forward(t*30)
    tortuepate.down()
    tortuepate.forward(t*50)
    tortuepate.up()
    tortuepate.forward(t*30)
    tortuepate.down()
    tortuepate.forward(t*35)

    tortuepate.up()
    tortuepate.goto(y,u)
    tortuepate.down()
    tortuepate.right(140)
    tortuepate.circle(t*15,40)
    tortuepate.circle(t*100,18)
    tortuepate.left(90)
    tortuepate.circle(t*-75,45)
    tortuepate.circle(t*30,50)
    tortuepate.right(15)
    tortuepate.circle(t*350,15)
    tortuepate.circle(t*-30,30)
    tortuepate.left(50)
    tortuepate.forward(t*28)
    tortuepate.end_fill()

    #Paquet 
    tortuepate.fillcolor('#e5cd9c')
    tortuepate.begin_fill()
    tortuepate.right(125)
    tortuepate.circle(t*-1600,8.7)
    tortuepate.right(20)
    tortuepate.circle(t*-60,70)
    tortuepate.left(3)
    tortuepate.forward(t*70)
    tortuepate.circle(t*-90,32)
    tortuepate.right(45)
    tortuepate.circle(t*-1600,8.4)
    tortuepate.right(78)
    tortuepate.circle(t*-75,45)
    tortuepate.circle(t*30,50)
    tortuepate.right(15)
    tortuepate.circle(t*350,15)
    tortuepate.circle(t*-30,30)
    tortuepate.left(50)
    tortuepate.forward(t*28)
    tortuepate.end_fill()

    tortuepate.up()
    tortuepate.right(127)
    tortuepate.circle(t*-1600,8.7)
    tortuepate.down()
    tortuepate.fillcolor('#e2261a')
    tortuepate.begin_fill()
    tortuepate.right(20)
    tortuepate.circle(t*-60,70)
    tortuepate.left(3)
    tortuepate.forward(t*70)
    tortuepate.circle(t*-90,30)
    tortuepate.left(126)
    tortuepate.forward(t*28)
    tortuepate.circle(t*10,80)
    tortuepate.right(15)
    tortuepate.circle(t*50,40)
    tortuepate.circle(t*-100,30)
    tortuepate.circle(t*200,19)
    tortuepate.circle(t*10,80)
    tortuepate.right(20)
    tortuepate.circle(t*70,34)
    tortuepate.end_fill()

    tortuepate.up()
    tortuepate.left(140)
    tortuepate.circle(t*-60,50)
    tortuepate.down()

    tortuepate.right(60)
    tortuepate.fillcolor('#126849')
    tortuepate.begin_fill()
    tortuepate.circle(t*70,93)
    tortuepate.end_fill()

    tortuepate.up()
    tortuepate.left(140)
    tortuepate.forward(t*8)
    tortuepate.left(30)

    tortuepate.fillcolor('white')
    tortuepate.begin_fill()
    tortuepate.circle(t*-70,75)
    tortuepate.end_fill()

    tortuepate.up()
    tortuepate.left(215)
    tortuepate.forward(t*20)
    tortuepate.right(20)
    tortuepate.fillcolor('red')
    tortuepate.begin_fill()
    tortuepate.circle(t*70,50)
    tortuepate.end_fill()

    tortuepate.up()
    tortuepate.right(113)
    tortuepate.forward(t*65)

    tortuepate.forward(t*165.5)
    tortuepate.right(80)
    tortuepate.forward(t*34)
    tortuepate.begin_fill()
    tortuepate.forward(t*20)
    tortuepate.right(97)
    tortuepate.forward(t*169)
    tortuepate.fillcolor('#126849')
    tortuepate.circle(t*-10,180)
    tortuepate.forward(t*165.5)
    tortuepate.end_fill()
    tortuepate.left(180)
    tortuepate.fillcolor('white')
    tortuepate.begin_fill()
    tortuepate.forward(t*165.5)
    tortuepate.right(90)
    tortuepate.circle(t*100,10)
    tortuepate.right(60)
    tortuepate.circle(t*10,50)
    f,g=tortuepate.pos()
    tortuepate.right(93)
    tortuepate.forward(t*165.5)
    tortuepate.right(90)
    tortuepate.forward(t*18)
    tortuepate.end_fill()

    tortuepate.up()
    tortuepate.goto(f,g)
    tortuepate.left(160)
    tortuepate.fillcolor('red')
    tortuepate.begin_fill()
    tortuepate.circle(t*10,100)
    tortuepate.right(168)
    tortuepate.forward(t*168.5)
    tortuepate.right(80)
    tortuepate.forward(t*20)
    tortuepate.end_fill()
    
    tortuepate.up()
    tortuepate.backward(t*75)
    tortuepate.right(90)
    tortuepate.forward(t*9)
    tortuepate.left(68)
    tortuepate.down()

    
    tortuepate.fillcolor('#126849')
    tortuepate.begin_fill()
    tortuepate.circle(t*400,23)
    tortuepate.circle(t*-5,110)
    tortuepate.circle(t*1600,2.1)
    tortuepate.circle(t*-5,73)
    tortuepate.circle(t*-300,28)
    tortuepate.circle(t*-5,80)
    tortuepate.circle(t*100,30)
    tortuepate.end_fill()

    tortuepate.pencolor('white')
    tortuepate.up()
    tortuepate.left(166)
    tortuepate.forward(t*60)
    tortuepate.down()
    tortuepate.write('PÂTES', font=("Arial",int(35*t), "normal"))
    
    
    update()
