from setup import *

def PQ (taille,x,y,angle=0):

    t=taille/12
    x+=500*t
    y+=500*t
    tortuepq=Turtle(undobuffersize=0,visible=False,shape="square")
    setup(x,y,angle,tortuepq)

    tortuepq.up()
    tortuepq.backward(t*300)
    tortuepq.left(90)
    tortuepq.forward(-30*t)
    tortuepq.down()
    
    tracer(0)
    tortuepq.left(75)

    tortuepq.width(2*t)


    tortuepq.pencolor('black')
    tortuepq.fillcolor('#FBCEF2')
    tortuepq.begin_fill()
    tortuepq.circle(1000*t,15)
    tortuepq.left(5)
    tortuepq.circle(1000*t,15)
    tortuepq.circle(50*t,50)
    tortuepq.circle(25*t,20)
    tortuepq.left(30)
    tortuepq.circle(25*t,20)
    tortuepq.circle(50*t,50)
    tortuepq.right(25)
    tortuepq.circle(1000*t,15)
    tortuepq.left(5)
    tortuepq.circle(1000*t,15)
    tortuepq.circle(50*t,50)
    tortuepq.circle(25*t,20)
    tortuepq.left(30)
    tortuepq.circle(25*t,20)
    tortuepq.circle(50*t,50)

    tortuepq.end_fill()
    tortuepq.up()
    tortuepq.right(25)
    tortuepq.forward(150*t)
    tortuepq.left(90)
    tortuepq.forward(50*t)
    tortuepq.right(90)
    tortuepq.down()
    
    i=0.7
    tortuepq.width(2*t)
    tortuepq.pencolor('black')
    tortuepq.fillcolor('#A17B66')
    tortuepq.begin_fill()
    tortuepq.circle(500*i*t,15)
    tortuepq.left(5)
    tortuepq.circle(500*i*t,15)
    tortuepq.circle(25*i*t,50)
    tortuepq.circle(12.5*i*t,20)
    tortuepq.left(30)
    tortuepq.circle(12.5*i*t,20)
    tortuepq.circle(25*i*t,50)
    tortuepq.right(25)
    tortuepq.circle(500*i*t,15)
    tortuepq.left(5)
    tortuepq.circle(500*i*t,15)
    tortuepq.circle(25*i*t,50)
    tortuepq.circle(12.5*i*t,20)
    tortuepq.left(30)
    tortuepq.circle(12.5*i*t,20)
    tortuepq.circle(25*i*t,50)
    tortuepq.end_fill()
   
    tortuepq.up()
    tortuepq.backward(198*t)
    tortuepq.left(90)
    tortuepq.forward(40*t)
    tortuepq.right(7)
    tortuepq.down()

    tortuepq.width(2*t)
    tortuepq.pencolor('black')
    tortuepq.fillcolor('#FBCEF2')
    tortuepq.begin_fill()
    tortuepq.forward(500*t)
    tortuepq.left(15)
    tortuepq.circle(-25*t,20)
    tortuepq.circle(-50*t,50)
    tortuepq.circle(-75*t,20)
    tortuepq.left(5)
    tortuepq.circle(-700*t,20)
    tortuepq.left(5)
    tortuepq.circle(-700*t,20)
    tortuepq.circle(-75*t,20)
    tortuepq.circle(-50*t,50)
    tortuepq.circle(-25*t,20)

    tortuepq.left(17)
    tortuepq.forward(505*t)

    tortuepq.right(153)
    tortuepq.circle(25*t,20)
    tortuepq.circle(50*t,50)
    tortuepq.right(25)
    tortuepq.circle(1000*t,15)
    tortuepq.left(5)
    tortuepq.circle(1000*t,15)
    tortuepq.circle(50*t,40)


    tortuepq.end_fill()

    tortuepq.width(2*t)
    tortuepq.pencolor('black')
    tortuepq.fillcolor('#FBCEF2')
    tortuepq.begin_fill()
    tortuepq.right(80)
    tortuepq.circle(-90*t,18)
    tortuepq.right(10)
    tortuepq.circle(-40*t,50)
    tortuepq.circle(-30*t,50)
    tortuepq.circle(-20*t,10)
    tortuepq.circle(-1000*t,1)
    tortuepq.end_fill()

    tortuepq.fillcolor('#FBCEF2')
    tortuepq.begin_fill()
    tortuepq.circle(-1000*t,14)
    tortuepq.left(90)
    tortuepq.forward(505*t)
    tortuepq.left(90)
    tortuepq.circle(500*t,30)
    tortuepq.circle(20*t,90)
    tortuepq.right(33)
    tortuepq.forward(480*t)
    tortuepq.left(185)
    tortuepq.circle(-40*t,50)
    tortuepq.circle(-30*t,50)
    tortuepq.circle(-20*t,10)
    tortuepq.end_fill()
    tortuepq.right(75)
    tortuepq.forward(70*t)
    update()
