from pynput.keyboard import Key, Controller
from time import sleep
keyboard = Controller()
sleep(5)
for i in range(50):
    keyboard.press(" ")
    sleep(1)
    keyboard.release(" ")
    sleep(1.5)
    keyboard.press("s")
    sleep(1)
    keyboard.release("s")
    sleep(0.5)
    keyboard.press(" ")
    sleep(1)
    keyboard.release(" ")
    sleep(1.5)
    keyboard.press("s")
    sleep(1)
    keyboard.release("s")
    sleep(0.5)
    keyboard.press("s")
    sleep(1)
    keyboard.release("s")
    sleep(0.5)
    keyboard.press(" ")
    sleep(1)
    keyboard.release(" ")
    sleep(1.5)
    keyboard.press(" ")
    sleep(1)
    keyboard.release(" ")
    sleep(1.5)
    keyboard.press(" ")
    sleep(1)
    keyboard.release(" ")
    sleep(2)

