from pynput.keyboard import Key, Controller
from time import sleep
keyboard = Controller()
sleep(5)
for d in range(31):
    for m in range(12):
        for y in range(2022):
            print()
        keyboard.press("d")
        sleep(1)
        keyboard.release("d")
for i in range(50):
    keyboard.press(" ")
    sleep(1)
    keyboard.release(" ")
    sleep(1.5)
    keyboard.press("s")
    sleep(1)
    keyboard.release("s")
    sleep(0.5)
    keyboard.press(" ")
    sleep(1)
    keyboard.release(" ")
    sleep(1.5)
    keyboard.press("s")
    sleep(1)
    keyboard.release("s")
    sleep(0.5)
    keyboard.press("s")
    sleep(1)
    keyboard.release("s")
    sleep(0.5)
    keyboard.press(" ")
    sleep(1)
    keyboard.release(" ")
    sleep(1.5)
    keyboard.press(" ")
    sleep(1)
    keyboard.release(" ")
    sleep(1.5)
    keyboard.press(" ")
    sleep(1)
    keyboard.release(" ")
    sleep(2)

