from turtle import *
from random import randint,choice
from math import cos,pi,sin
from time import sleep
from etagere import *
from Quillebaguette import *
from Quillebonbon import *
from Quilleboule import *
from Quillecafe import *
from Quillecalculatrice import *
from Quillechat import *
from Quillechaussette import *
from Quillecoca import *
from Quillecouteau import *
from pion import *
from Quilledé import *
from Quillelivrequdeux import *
from Quillelivretrsept import *
from Quillemasque import *
from Quillepate import *
from Quillepokeball import *
from QuillePQ import *
from Quillesmasterpomme import *
from Quilletournevis import *
from Quillewumpus import *
from stock import *
from Cadi import *
from pancovid import *

#fonction afficherquilles : par une liste en compréhension, on parcourt les sous listes de c, et on join les sous-chaines, puis on y ajoute le début et la fin de la ligne de quilles, avec des quilles tombées.
def afficherquilles(c,nlim):
    return "-"*(c[0][0]-1)+"".join(["-"*(c[i][0]-c[i-1][1])+"|"*(c[i][1]-c[i][0])+"-"*(nlim-c[len(c)-1][1]) for i in range(0,len(c))])+" "
def gotopourcent(x,y,tortue=Turtle()):
    tortue.goto((x/100-0.5)*window_width(),(y/100-0.5)*window_height())
def ovalerelatif(tortue,prec,longueur,ecrasement,scale=1):
    for i in range(prec):
        tortue.forward((longueur+ecrasement*cos(i/prec*2*pi*2))*scale)
        tortue.left(360/prec)
def tomate(ecran,scale=1,x=0,y=0):
    tortuetomate=Turtle(undobuffersize=0,visible=False,shape="square")
    tomate = Shape("compound")
    tortuetomate.penup()
    tortuetomate.speed(0)
    scale=scale/8
    direction=tortuetomate.heading()
    y-=10
    tortuetomate.goto(x,y)
    tortuetomate.pendown()
    tortuetomate.pencolor("#000000")
    tortuetomate.fillcolor("#dd3131")
    tortuetomate.begin_poly()
    tortuetomate.pensize(2*scale)
    ovalerelatif(tortuetomate,60,12,6,scale)
    tortuetomate.end_poly()
    tomate.addcomponent(tortuetomate.get_poly(),tortuetomate.fillcolor(),tortuetomate.pencolor())
    tortuetomate.penup()
    tortuetomate.goto(x+60*scale,y+120*scale)
    tortuetomate.pendown()
    tortuetomate.pencolor("#d06b2b")
    tortuetomate.fillcolor("#ffff00")
    tortuetomate.begin_poly()
    tortuetomate.pensize(4*scale)
    ovalerelatif(tortuetomate,30,4,4,scale)
    tortuetomate.end_poly()
    tomate.addcomponent(tortuetomate.get_poly(),tortuetomate.fillcolor(),tortuetomate.pencolor())
    tortuetomate.penup()
    tortuetomate.goto(x,y+180*scale)
    tortuetomate.pendown()
    tortuetomate.pencolor("#000000")
    tortuetomate.fillcolor("#155216")
    tortuetomate.begin_poly()
    tortuetomate.pensize(2*scale)
    tortuetomate.left(15)
    tortuetomate.circle(scale*60,30)
    tortuetomate.left(172.5)
    tortuetomate.circle(scale*40,-55)
    tortuetomate.end_poly()
    tomate.addcomponent(tortuetomate.get_poly(),tortuetomate.fillcolor(),tortuetomate.pencolor())
    tortuetomate.goto(x,y+180*scale)
    tortuetomate.left(0)
    tortuetomate.begin_poly()
    tortuetomate.pensize(2*scale)
    tortuetomate.left(15)
    tortuetomate.circle(scale*-60,30)
    tortuetomate.left(172.5)
    tortuetomate.circle(scale*-40,-55)
    tortuetomate.end_poly()
    tomate.addcomponent(tortuetomate.get_poly(),tortuetomate.fillcolor(),tortuetomate.pencolor())
    tortuetomate.goto(x,y+180*scale)
    tortuetomate.begin_poly()
    tortuetomate.pensize(2*scale)
    tortuetomate.left(210)
    tortuetomate.circle(scale*-60,30)
    tortuetomate.left(172.5)
    tortuetomate.circle(scale*-40,-55)
    tortuetomate.end_poly()
    tomate.addcomponent(tortuetomate.get_poly(),tortuetomate.fillcolor(),tortuetomate.pencolor())
    tortuetomate.goto(x,y+180*scale)
    tortuetomate.begin_poly()
    tortuetomate.right(60)
    tortuetomate.forward(5*scale)
    tortuetomate.circle(5*scale,90)
    tortuetomate.forward(40*scale)
    tortuetomate.circle(10*scale,180)
    tortuetomate.forward(40*scale)
    tortuetomate.circle(5*scale,90)
    tortuetomate.forward(5*scale)
    tortuetomate.end_poly()
    tomate.addcomponent(tortuetomate.get_poly(),tortuetomate.fillcolor(),tortuetomate.pencolor())
    tortuetomate.penup()
    tortuetomate.setheading(direction)
    ecran.addshape('tomate', shape=tomate)
def voiture(ecran,scale=1,x=0,y=0,miroir=1):
    tortuevoiture=Turtle(undobuffersize=0,visible=False,shape="square")
    scale=scale/5
    voiture = Shape("compound")

    tortuevoiture.pencolor("#000000")
    tortuevoiture.fillcolor("#0070b6")
    tortuevoiture.penup()
    tortuevoiture.pensize(2*scale)
    direction=heading()
    tortuevoiture.forward(x)
    tortuevoiture.left(miroir*90)
    tortuevoiture.forward(y)
    tortuevoiture.right(miroir*90)
    x7,y7=tortuevoiture.pos()
    tortuevoiture.right(miroir*90)
    tortuevoiture.forward(scale*67)
    x6,y6=tortuevoiture.pos()
    tortuevoiture.pendown()                               #carosserie
    tortuevoiture.begin_poly()
    tortuevoiture.left(miroir*90)
    tortuevoiture.forward(scale*68)
    tortuevoiture.left(miroir*115)
    x4,y4=tortuevoiture.pos()
    tortuevoiture.circle(miroir*scale*-37,230)
    tortuevoiture.right(miroir*245)
    tortuevoiture.forward(scale*10)
    (x2,y2)=tortuevoiture.pos()
    tortuevoiture.left(miroir*90)
    tortuevoiture.forward(scale*20)
    tortuevoiture.right(miroir*45)
    update()
    tortuevoiture.forward(scale*5)
    tortuevoiture.right(miroir*55)
    tortuevoiture.circle(miroir*scale*100,29)
    tortuevoiture.left(miroir*64)
    tortuevoiture.circle(miroir*scale*150,21)
    x3,y3=tortuevoiture.pos()
    tortuevoiture.circle(miroir*scale*150,9)
    tortuevoiture.circle(miroir*scale*30,21)
    tortuevoiture.forward(scale*75)
    tortuevoiture.right(miroir*45)
    tortuevoiture.circle(miroir*scale*10,85)
    tortuevoiture.circle(miroir*scale*900,10)
    tortuevoiture.circle(miroir*scale*20,60)
    tortuevoiture.circle(miroir*scale*-5,12)
    tortuevoiture.forward(scale*70)
    tortuevoiture.circle(miroir*scale*-5,45)
    tortuevoiture.forward(scale*30)
    tortuevoiture.left(miroir*10)
    tortuevoiture.forward(scale*30)
    tortuevoiture.left(miroir*10)
    tortuevoiture.circle(miroir*scale*50,50)
    tortuevoiture.forward(scale*37)
    tortuevoiture.left(miroir*80)
    tortuevoiture.circle(miroir*scale*100,37)
    tortuevoiture.right(miroir*80)
    tortuevoiture.circle(miroir*scale*-25,45)
    tortuevoiture.left(miroir*105)
    tortuevoiture.forward(scale*20)
    tortuevoiture.left(miroir*120)
    tortuevoiture.circle(miroir*scale*-37,230)
    x5,y5=tortuevoiture.pos()
    tortuevoiture.right(miroir*245)
    tortuevoiture.forward(scale*41)
    tortuevoiture.end_poly()
    voiture.addcomponent(tortuevoiture.get_poly(),tortuevoiture.fillcolor(),tortuevoiture.pencolor())
    tortuevoiture.penup()
    tortuevoiture.forward(scale*127)
    tortuevoiture.left(miroir*90)
    tortuevoiture.forward(scale*169)
    tortuevoiture.left(miroir*91)
    tortuevoiture.pendown()                               #toit
    tortuevoiture.forward(scale*183)
    tortuevoiture.penup()
    tortuevoiture.left(miroir*160)
    tortuevoiture.forward(scale*20)
    tortuevoiture.left(miroir*20)
    tortuevoiture.pendown()                               #portière
    tortuevoiture.forward(scale*65)
    tortuevoiture.circle(miroir*scale*-9,90)
    tortuevoiture.forward(scale*53)
    tortuevoiture.left(miroir*22)
    tortuevoiture.forward(scale*10)
    tortuevoiture.right(miroir*22)
    tortuevoiture.forward(scale*74)
    tortuevoiture.right(miroir*90)
    tortuevoiture.forward(scale*74)
    tortuevoiture.right(miroir*90)
    tortuevoiture.circle(miroir*scale*50,75)
    tortuevoiture.right(miroir*75)
    tortuevoiture.forward(scale*30)
    tortuevoiture.left(miroir*45)
    tortuevoiture.forward(scale*10)
    tortuevoiture.right(miroir*45)
    tortuevoiture.forward(scale*7)
    tortuevoiture.right(miroir*45)
    tortuevoiture.forward(scale*10)
    tortuevoiture.left(miroir*45)
    tortuevoiture.forward(scale*6)
    tortuevoiture.right(miroir*40)
    tortuevoiture.forward(scale*52)
    tortuevoiture.penup()
    tortuevoiture.right(miroir*50)
    tortuevoiture.forward(scale*17)
    tortuevoiture.right(miroir*90)
    tortuevoiture.forward(scale*5)
    tortuevoiture.left(miroir*90)
    tortuevoiture.fillcolor("#90e8fb")
    tortuevoiture.begin_poly()
    tortuevoiture.pendown()                               #première fenètre
    tortuevoiture.forward(scale*40)
    tortuevoiture.circle(miroir*scale*-7,90)
    tortuevoiture.forward(scale*45)
    tortuevoiture.circle(miroir*scale*-7,90)
    tortuevoiture.forward(scale*52)
    x1,y1=tortuevoiture.pos()
    tortuevoiture.right(miroir*40)
    tortuevoiture.forward(scale*37)
    tortuevoiture.right(miroir*87)
    tortuevoiture.forward(scale*37)
    tortuevoiture.circle(miroir*scale*-13,53)
    tortuevoiture.forward(scale*7)
    tortuevoiture.end_poly()
    voiture.addcomponent(tortuevoiture.get_poly(),tortuevoiture.fillcolor(),tortuevoiture.pencolor())
    tortuevoiture.penup()
    tortuevoiture.goto(x1,y1)
    tortuevoiture.forward(scale*90)
    tortuevoiture.begin_poly()
    tortuevoiture.pendown()                               #deuxieme fenètre
    tortuevoiture.forward(scale*88)
    tortuevoiture.circle(miroir*scale*6,127)
    tortuevoiture.forward(scale*55)
    tortuevoiture.circle(miroir*scale*10,53)
    tortuevoiture.forward(scale*53)
    tortuevoiture.circle(miroir*scale*6,90)
    tortuevoiture.forward(scale*46)
    tortuevoiture.circle(miroir*scale*6,90)
    tortuevoiture.end_poly()
    voiture.addcomponent(tortuevoiture.get_poly(),tortuevoiture.fillcolor(),tortuevoiture.pencolor())
    tortuevoiture.penup()
    tortuevoiture.goto(x1,y1)
    tortuevoiture.right(miroir*90)
    tortuevoiture.pendown()                               #rétroviseur
    tortuevoiture.fillcolor("#cdcdcd")
    tortuevoiture.begin_poly()
    tortuevoiture.circle(miroir*scale*-3,90)
    tortuevoiture.forward(scale*27)
    tortuevoiture.circle(miroir*scale*-3,90)
    tortuevoiture.forward(scale*19)
    tortuevoiture.circle(miroir*scale*-3,90)
    tortuevoiture.forward(scale*27)
    tortuevoiture.circle(miroir*scale*-3,90)
    tortuevoiture.forward(scale*19)
    tortuevoiture.end_poly()
    voiture.addcomponent(tortuevoiture.get_poly(),tortuevoiture.fillcolor(),tortuevoiture.pencolor())
    tortuevoiture.circle(miroir*scale*-3,90)
    tortuevoiture.forward(scale*27)
    tortuevoiture.circle(miroir*scale*-3,90)
    tortuevoiture.forward(scale*17)
    tortuevoiture.right(miroir*90)
    tortuevoiture.forward(scale*19)
    tortuevoiture.right(miroir*20)
    tortuevoiture.circle(miroir*scale*-10,90)
    tortuevoiture.penup()
    tortuevoiture.right(miroir*70)
    tortuevoiture.goto(x6,y6)
    tortuevoiture.forward(scale*132)
    tortuevoiture.fillcolor("#d00000")
    tortuevoiture.begin_poly()
    tortuevoiture.left(miroir*25)
    tortuevoiture.pendown()                               #truc rouge devant
    tortuevoiture.circle(miroir*scale*-70,58)
    tortuevoiture.right(miroir*60)
    tortuevoiture.forward(scale*19)
    tortuevoiture.right(miroir*45)
    tortuevoiture.forward(scale*8)
    tortuevoiture.right(miroir*65)
    tortuevoiture.circle(miroir*scale*100,37)
    tortuevoiture.right(miroir*80)
    tortuevoiture.circle(miroir*scale*-25,60)
    tortuevoiture.end_poly()
    voiture.addcomponent(tortuevoiture.get_poly(),tortuevoiture.fillcolor(),tortuevoiture.pencolor())
    tortuevoiture.right(miroir*30)
    tortuevoiture.circle(miroir*scale*-70,58)
    tortuevoiture.right(miroir*60)
    tortuevoiture.forward(scale*19)
    tortuevoiture.right(miroir*110)
    tortuevoiture.circle(miroir*scale*100,37)
    tortuevoiture.penup()
    tortuevoiture.left(miroir*150)
    tortuevoiture.forward(scale*57)
    tortuevoiture.fillcolor("#ffda3f")
    tortuevoiture.pendown()                               #phare avant
    tortuevoiture.begin_poly()
    tortuevoiture.circle(miroir*scale*-5,60)
    tortuevoiture.circle(miroir*scale*-40,50)
    tortuevoiture.right(miroir*75)
    tortuevoiture.circle(miroir*scale*60,24)
    tortuevoiture.right(miroir*110)
    tortuevoiture.circle(miroir*scale*60,32)
    tortuevoiture.right(miroir*80)
    tortuevoiture.circle(miroir*scale*-20,35)
    tortuevoiture.right(miroir*60)
    tortuevoiture.circle(miroir*scale*-40,52)
    tortuevoiture.left(miroir*180)
    tortuevoiture.circle(miroir*scale*40,52)
    tortuevoiture.right(miroir*100)
    tortuevoiture.circle(miroir*scale*-40,25)
    tortuevoiture.left(miroir*16)
    tortuevoiture.end_poly()
    voiture.addcomponent(tortuevoiture.get_poly(),tortuevoiture.fillcolor(),tortuevoiture.pencolor())
    tortuevoiture.penup()
    tortuevoiture.goto(x2,y2)
    tortuevoiture.fillcolor("#d00000")
    tortuevoiture.begin_poly()
    tortuevoiture.pendown()                               #truc rouge arrière
    tortuevoiture.left(miroir*90)
    tortuevoiture.forward(scale*5)
    tortuevoiture.left(miroir*45)
    tortuevoiture.forward(scale*5)
    tortuevoiture.left(miroir*40)
    tortuevoiture.circle(miroir*scale*120,25)
    tortuevoiture.circle(miroir*scale*9,60)
    tortuevoiture.circle(miroir*scale*40,28)
    tortuevoiture.left(miroir*105)
    tortuevoiture.circle(miroir*scale*-74,48)
    tortuevoiture.left(miroir*180)
    tortuevoiture.circle(miroir*scale*74,48)
    tortuevoiture.left(miroir*105)
    tortuevoiture.forward(scale*6)
    tortuevoiture.left(miroir*62)
    tortuevoiture.circle(miroir*scale*-100,29)
    tortuevoiture.left(miroir*55)
    tortuevoiture.forward(scale*7)
    tortuevoiture.left(miroir*45)
    tortuevoiture.forward(scale*20)
    tortuevoiture.right(miroir*91)
    tortuevoiture.end_poly()
    voiture.addcomponent(tortuevoiture.get_poly(),tortuevoiture.fillcolor(),tortuevoiture.pencolor())
    tortuevoiture.penup()
    tortuevoiture.goto(x3,y3)
    tortuevoiture.fillcolor("#ffda3f")
    tortuevoiture.pendown()                               #phare arrière
    tortuevoiture.begin_poly()
    tortuevoiture.circle(miroir*scale*16,50)
    tortuevoiture.left(miroir*40)
    tortuevoiture.forward(scale*12)
    tortuevoiture.left(miroir*90)
    tortuevoiture.forward(scale*16)
    tortuevoiture.left(miroir*180)
    tortuevoiture.forward(scale*16)
    tortuevoiture.left(miroir*90)
    tortuevoiture.forward(scale*28)
    tortuevoiture.left(miroir*60)
    tortuevoiture.circle(miroir*scale*20,50)
    tortuevoiture.left(miroir*66)
    tortuevoiture.circle(miroir*scale*150,18)
    tortuevoiture.end_poly()
    voiture.addcomponent(tortuevoiture.get_poly(),tortuevoiture.fillcolor(),tortuevoiture.pencolor())
    tortuevoiture.penup()
    tortuevoiture.goto(x4,y4)
    tortuevoiture.left(miroir*10)
    tortuevoiture.pendown()                               #roue arrière
    tortuevoiture.fillcolor("#000000")
    tortuevoiture.begin_poly()
    tortuevoiture.circle(miroir*scale*-37)
    tortuevoiture.end_poly()
    voiture.addcomponent(tortuevoiture.get_poly(),tortuevoiture.fillcolor(),tortuevoiture.pencolor())
    tortuevoiture.right(miroir*90)
    tortuevoiture.forward(scale*23)
    tortuevoiture.left(miroir*90)
    tortuevoiture.fillcolor("#ffffff")
    tortuevoiture.begin_poly()
    tortuevoiture.circle(miroir*scale*-14)
    tortuevoiture.end_poly()
    voiture.addcomponent(tortuevoiture.get_poly(),tortuevoiture.fillcolor(),tortuevoiture.pencolor())
    tortuevoiture.penup()
    tortuevoiture.goto(x5,y5)
    tortuevoiture.pendown()
    tortuevoiture.right(miroir*50)
    tortuevoiture.fillcolor("#000000")
    tortuevoiture.begin_poly()
    tortuevoiture.circle(miroir*scale*37)
    tortuevoiture.end_poly()
    voiture.addcomponent(tortuevoiture.get_poly(),tortuevoiture.fillcolor(),tortuevoiture.pencolor())
    tortuevoiture.left(miroir*90)
    tortuevoiture.forward(scale*23)
    tortuevoiture.right(miroir*90)
    tortuevoiture.fillcolor("#ffffff")
    tortuevoiture.begin_poly()
    tortuevoiture.circle(miroir*scale*14)
    tortuevoiture.end_poly()
    voiture.addcomponent(tortuevoiture.get_poly(),tortuevoiture.fillcolor(),tortuevoiture.pencolor())
    tortuevoiture.right(miroir*64)
    tortuevoiture.penup()
    tortuevoiture.goto(x6,y6)
    tortuevoiture.left(miroir*90)
    tortuevoiture.forward(scale*80)
    tortuevoiture.left(miroir*90)
    tortuevoiture.forward(scale*5)
    tortuevoiture.right(miroir*90)
    tortuevoiture.fillcolor("#cdcdcd")
    tortuevoiture.begin_poly()
    tortuevoiture.pendown()                               #poignée
    tortuevoiture.forward(scale*5)
    tortuevoiture.right(miroir*110)
    tortuevoiture.circle(miroir*scale*23,40)
    tortuevoiture.pendown()
    tortuevoiture.right(miroir*110)
    tortuevoiture.forward(scale*5)
    tortuevoiture.right(miroir*70)
    tortuevoiture.circle(miroir*scale*-23,40)
    tortuevoiture.end_poly()
    voiture.addcomponent(tortuevoiture.get_poly(),tortuevoiture.fillcolor(),tortuevoiture.pencolor())
    setheading(direction)
    ecran.addshape('voiture', shape=voiture)
def halteres(ecran,scale=1,x=0,y=0,miroir=1):
    tortuehalteres=Turtle(undobuffersize=0,visible=False,shape="square")
    halteres = Shape("compound")
    tortuehalteres.pencolor("#000000")
    tortuehalteres.fillcolor("#edf0f1")
    scale=scale/7
    tortuehalteres.penup()
    tortuehalteres.pensize(10*scale)
    direction=tortuehalteres.heading()
    tortuehalteres.goto(x,y)
    tortuehalteres.left(miroir*90)
    tortuehalteres.forward(scale*21)
    tortuehalteres.right(miroir*90)
    tortuehalteres.pendown()                               #barre
    tortuehalteres.begin_poly()
    tortuehalteres.forward(scale*285)
    tortuehalteres.circle(miroir*scale*-10,90)
    tortuehalteres.forward(scale*22)
    tortuehalteres.circle(miroir*scale*-10,90)
    tortuehalteres.forward(scale*570)
    tortuehalteres.circle(miroir*scale*-10,90)
    tortuehalteres.forward(scale*22)
    tortuehalteres.circle(miroir*scale*-10,90)
    tortuehalteres.forward(scale*285)
    tortuehalteres.end_poly()
    halteres.addcomponent(tortuehalteres.get_poly(),tortuehalteres.fillcolor(),tortuehalteres.pencolor())
    tortuehalteres.forward(scale*137)
    tortuehalteres.fillcolor("#bfc5c8")
    tortuehalteres.begin_poly()
    tortuehalteres.left(miroir*90)
    tortuehalteres.forward(scale*10)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*10)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*62)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*10)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*52)
    tortuehalteres.end_poly()
    halteres.addcomponent(tortuehalteres.get_poly(),tortuehalteres.fillcolor(),tortuehalteres.pencolor())
    tortuehalteres.right(miroir*90)
    tortuehalteres.penup()
    tortuehalteres.forward(scale*134)
    tortuehalteres.pendown()
    tortuehalteres.begin_poly()
    tortuehalteres.left(miroir*90)
    tortuehalteres.forward(scale*20)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*13)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*82)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*13)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*62)
    tortuehalteres.end_poly()
    halteres.addcomponent(tortuehalteres.get_poly(),tortuehalteres.fillcolor(),tortuehalteres.pencolor())
    tortuehalteres.fillcolor("#3d3f46")
    tortuehalteres.begin_poly()
    tortuehalteres.forward(scale*55)
    tortuehalteres.circle(miroir*miroir*miroir*scale*21,180)
    tortuehalteres.forward(scale*152)
    tortuehalteres.circle(miroir*miroir*miroir*scale*21,180)
    tortuehalteres.forward(scale*97)
    tortuehalteres.end_poly()
    halteres.addcomponent(tortuehalteres.get_poly(),tortuehalteres.fillcolor(),tortuehalteres.pencolor())
    tortuehalteres.penup()
    tortuehalteres.left(miroir*90)
    tortuehalteres.forward(scale*42)
    tortuehalteres.right(miroir*90)
    tortuehalteres.pendown()
    tortuehalteres.begin_poly()
    tortuehalteres.forward(scale*75)
    tortuehalteres.circle(miroir*miroir*miroir*scale*21,180)
    tortuehalteres.forward(scale*192)
    tortuehalteres.circle(miroir*miroir*miroir*scale*21,180)
    tortuehalteres.forward(scale*117)
    tortuehalteres.end_poly()
    halteres.addcomponent(tortuehalteres.get_poly(),tortuehalteres.fillcolor(),tortuehalteres.pencolor())
    tortuehalteres.penup()
    tortuehalteres.left(miroir*90)
    tortuehalteres.forward(scale*42)
    tortuehalteres.right(miroir*90)

    tortuehalteres.pendown()
    tortuehalteres.begin_poly()
    tortuehalteres.forward(scale*95)
    tortuehalteres.circle(miroir*miroir*miroir*scale*21,180)
    tortuehalteres.forward(scale*232)
    tortuehalteres.circle(miroir*miroir*miroir*scale*21,180)
    tortuehalteres.forward(scale*137)
    tortuehalteres.end_poly()
    halteres.addcomponent(tortuehalteres.get_poly(),tortuehalteres.fillcolor(),tortuehalteres.pencolor())
    tortuehalteres.penup()
    tortuehalteres.left(miroir*90)
    tortuehalteres.forward(scale*42)
    tortuehalteres.right(miroir*90)
    
    tortuehalteres.penup()
    tortuehalteres.forward(scale*-42)
    tortuehalteres.left(miroir*90)
    tortuehalteres.forward(scale*283)
    
    tortuehalteres.fillcolor("#bfc5c8")
    tortuehalteres.pendown()
    tortuehalteres.begin_poly()
    tortuehalteres.left(miroir*90)
    tortuehalteres.forward(scale*10)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*10)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*62)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*10)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*52)
    tortuehalteres.end_poly()
    halteres.addcomponent(tortuehalteres.get_poly(),tortuehalteres.fillcolor(),tortuehalteres.pencolor())
    tortuehalteres.right(miroir*90)
    tortuehalteres.penup()
    tortuehalteres.forward(scale*134)
    tortuehalteres.pendown()
    tortuehalteres.begin_poly()
    tortuehalteres.left(miroir*90)
    tortuehalteres.forward(scale*20)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*13)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*82)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*13)
    tortuehalteres.right(miroir*90)
    tortuehalteres.forward(scale*62)
    tortuehalteres.end_poly()
    halteres.addcomponent(tortuehalteres.get_poly(),tortuehalteres.fillcolor(),tortuehalteres.pencolor())
    tortuehalteres.fillcolor("#3d3f46")
    tortuehalteres.begin_poly()
    tortuehalteres.forward(scale*55)
    tortuehalteres.circle(miroir*miroir*miroir*scale*21,180)
    tortuehalteres.forward(scale*152)
    tortuehalteres.circle(miroir*miroir*miroir*scale*21,180)
    tortuehalteres.forward(scale*97)
    tortuehalteres.end_poly()
    halteres.addcomponent(tortuehalteres.get_poly(),tortuehalteres.fillcolor(),tortuehalteres.pencolor())
    tortuehalteres.penup()
    tortuehalteres.left(miroir*90)
    tortuehalteres.forward(scale*42)
    tortuehalteres.right(miroir*90)

    tortuehalteres.pendown()
    tortuehalteres.begin_poly()
    tortuehalteres.forward(scale*75)
    tortuehalteres.circle(miroir*miroir*miroir*scale*21,180)
    tortuehalteres.forward(scale*192)
    tortuehalteres.circle(miroir*miroir*miroir*scale*21,180)
    tortuehalteres.forward(scale*117)
    tortuehalteres.end_poly()
    halteres.addcomponent(tortuehalteres.get_poly(),tortuehalteres.fillcolor(),tortuehalteres.pencolor())
    tortuehalteres.penup()
    tortuehalteres.left(miroir*90)
    tortuehalteres.forward(scale*42)
    tortuehalteres.right(miroir*90)

    tortuehalteres.pendown()
    tortuehalteres.begin_poly()
    tortuehalteres.forward(scale*95)
    tortuehalteres.circle(miroir*miroir*miroir*scale*21,180)
    tortuehalteres.forward(scale*232)
    tortuehalteres.circle(miroir*miroir*miroir*scale*21,180)
    tortuehalteres.forward(scale*137)
    tortuehalteres.end_poly()
    halteres.addcomponent(tortuehalteres.get_poly(),tortuehalteres.fillcolor(),tortuehalteres.pencolor())
    tortuehalteres.penup()
    tortuehalteres.left(miroir*90)
    tortuehalteres.forward(scale*42)
    tortuehalteres.right(miroir*90)
    tortuehalteres.setheading(direction)
    ecran.addshape('halteres', shape=halteres)
def caleçon(ecran,scale=1,x=0,y=0,miroir=1):
    tortuecaleçon=Turtle(undobuffersize=0,visible=False,shape="square")
    caleçon = Shape("compound")
    tortuecaleçon.pencolor("#000000")
    tortuecaleçon.fillcolor("#000000")
    scale=scale/3
    tortuecaleçon.penup()
    tortuecaleçon.pensize(2*scale)
    direction=heading()
    tortuecaleçon.goto(x,y)
    tortuecaleçon.left(miroir*90)
    tortuecaleçon.forward(scale*47)
    tortuecaleçon.right(miroir*90)
    tortuecaleçon.pendown()
    tortuecaleçon.begin_poly()
    tortuecaleçon.forward(scale*70)
    tortuecaleçon.left(miroir*100)
    tortuecaleçon.forward(scale*20)
    tortuecaleçon.pencolor("#ffffff")
    tortuecaleçon.left(miroir*80)
    tortuecaleçon.forward(scale*135)
    tortuecaleçon.left(miroir*80)
    tortuecaleçon.pencolor("#000000")
    tortuecaleçon.forward(scale*20)
    tortuecaleçon.left(miroir*100)
    tortuecaleçon.forward(scale*70)
    tortuecaleçon.end_poly()
    caleçon.addcomponent(tortuecaleçon.get_poly(),tortuecaleçon.fillcolor(),tortuecaleçon.pencolor())
    tortuecaleçon.fillcolor("#004680")
    tortuecaleçon.begin_poly()
    tortuecaleçon.forward(scale*72)
    tortuecaleçon.right(miroir*80)
    tortuecaleçon.forward(scale*25)
    tortuecaleçon.circle(scale*-190,8)
    tortuecaleçon.forward(scale*53)
    tortuecaleçon.right(miroir*65)
    tortuecaleçon.circle(scale*-100,41)
    tortuecaleçon.right(miroir*70)
    tortuecaleçon.forward(scale*15)
    tortuecaleçon.circle(scale*7,175)
    tortuecaleçon.forward(scale*15)
    tortuecaleçon.right(miroir*80)
    tortuecaleçon.circle(scale*-100,46)
    tortuecaleçon.right(miroir*59)
    tortuecaleçon.forward(scale*53)
    tortuecaleçon.circle(scale*-190,8)
    tortuecaleçon.forward(scale*19)
    tortuecaleçon.right(miroir*79)
    tortuecaleçon.forward(scale*72)
    tortuecaleçon.end_poly()
    caleçon.addcomponent(tortuecaleçon.get_poly(),tortuecaleçon.fillcolor(),tortuecaleçon.pencolor())
    tortuecaleçon.penup()
    tortuecaleçon.forward(scale*-68)
    tortuecaleçon.left(90)
    tortuecaleçon.forward(scale*-50)
    tortuecaleçon.pencolor("#ffffff")
    tortuecaleçon.setheading(direction)
    ecran.addshape('caleçon', shape=caleçon)
def lit(ecran,scale=1,x=0,y=0,miroir=1):
    tortuelit=Turtle(undobuffersize=0,visible=False,shape="square")
    lit = Shape("compound")
    tortuelit.pencolor("#000000")
    tortuelit.fillcolor("#80201f")
    tortuelit.penup()
    scale=scale/2
    x2,y2=pos()
    tortuelit.pensize(2*scale)
    direction=tortuelit.heading()
    tortuelit.goto(x,y+10*scale)
    tortuelit.forward(scale*-74)
    tortuelit.left(miroir*90)
    tortuelit.forward(scale*5)
    tortuelit.right(miroir*63)
    tortuelit.pendown()
    tortuelit.begin_poly()
    tortuelit.forward(scale*81)
    tortuelit.right(miroir*54)
    tortuelit.forward(scale*55)
    tortuelit.right(miroir*126)
    tortuelit.forward(scale*81)
    tortuelit.right(miroir*54)
    tortuelit.forward(scale*55)
    tortuelit.left(miroir*117)
    tortuelit.end_poly()
    lit.addcomponent(tortuelit.get_poly(),tortuelit.fillcolor(),tortuelit.pencolor())
    tortuelit.fillcolor("#5f1918")
    tortuelit.begin_poly()
    tortuelit.forward(scale*15)
    tortuelit.left(miroir*63)
    tortuelit.forward(scale*55)
    tortuelit.left(miroir*117)
    x1,y1=tortuelit.pos()
    tortuelit.forward(scale*15)
    tortuelit.end_poly()
    lit.addcomponent(tortuelit.get_poly(),tortuelit.fillcolor(),tortuelit.pencolor())
    tortuelit.fillcolor("#300605")
    tortuelit.begin_poly()
    tortuelit.forward(scale*-15)
    tortuelit.right(miroir*63)
    tortuelit.forward(scale*81)
    tortuelit.left(miroir*63)
    tortuelit.forward(scale*15)
    tortuelit.end_poly()
    lit.addcomponent(tortuelit.get_poly(),tortuelit.fillcolor(),tortuelit.pencolor())
    tortuelit.fillcolor("#626161")
    tortuelit.begin_poly()
    tortuelit.forward(scale*-15)
    tortuelit.right(miroir*63)
    tortuelit.forward(scale*29)
    tortuelit.left(miroir*63)
    tortuelit.forward(scale*15)
    tortuelit.left(miroir*117)
    tortuelit.forward(scale*29)
    tortuelit.end_poly()
    lit.addcomponent(tortuelit.get_poly(),tortuelit.fillcolor(),tortuelit.pencolor())
    tortuelit.fillcolor("#dfe0e2")
    tortuelit.begin_poly()
    tortuelit.forward(scale*-29)
    tortuelit.right(miroir*54)
    tortuelit.forward(scale*55)
    tortuelit.left(miroir*54)
    tortuelit.forward(scale*29)
    tortuelit.end_poly()
    lit.addcomponent(tortuelit.get_poly(),tortuelit.fillcolor(),tortuelit.pencolor())
    tortuelit.penup()
    tortuelit.goto(x1,y1)
    tortuelit.pendown()
    tortuelit.left(miroir*63)
    tortuelit.fillcolor("#392714")
    tortuelit.begin_poly()
    tortuelit.forward(scale*17)
    tortuelit.left(miroir*117)
    tortuelit.forward(scale*11)
    tortuelit.left(miroir*63)
    tortuelit.forward(scale*11)
    tortuelit.right(miroir*63)
    tortuelit.forward(scale*90)
    tortuelit.right(miroir*117)
    tortuelit.forward(scale*11)
    tortuelit.left(miroir*117)
    tortuelit.forward(scale*9)
    tortuelit.left(miroir*63)
    tortuelit.forward(scale*17)
    tortuelit.end_poly()
    lit.addcomponent(tortuelit.get_poly(),tortuelit.fillcolor(),tortuelit.pencolor())
    tortuelit.penup()
    tortuelit.goto(x1,y1)
    tortuelit.pendown()
    tortuelit.fillcolor("#57391f")
    tortuelit.begin_poly()
    tortuelit.forward(scale*-17)
    tortuelit.left(miroir*63)
    tortuelit.forward(scale*11)
    tortuelit.right(miroir*63)
    tortuelit.forward(scale*11)
    tortuelit.left(miroir*63)
    tortuelit.forward(scale*33)
    tortuelit.right(miroir*63)
    tortuelit.forward(scale*-11)
    tortuelit.left(miroir*63)
    tortuelit.forward(scale*11)
    tortuelit.right(miroir*63)
    tortuelit.forward(scale*17)
    tortuelit.end_poly()
    lit.addcomponent(tortuelit.get_poly(),tortuelit.fillcolor(),tortuelit.pencolor())
    tortuelit.penup()
    tortuelit.goto(x2,y2)
    tortuelit.setheading(direction)
    ecran.addshape('lit', shape=lit)
def soleil(x,y,freq=10,tortue=Turtle()):
    gotopourcent(x+2,y,tortue)
    tortue.pendown()
    tortue.fillcolor("#ffff00")
    tortue.begin_fill()
    for t in range(100):
        gotopourcent(2*cos(t/100*2*pi)+x,2*sin(t/100*2*pi)+y,tortue)
        if t%freq==0:
            tortue.pencolor("#ffff00")
            gotopourcent(5*cos(t/100*2*pi)+x,5*sin(t/100*2*pi)+y,tortue)
            gotopourcent(2*cos(t/100*2*pi)+x,2*sin(t/100*2*pi)+y,tortue)
            tortue.pencolor("#000000")
    tortue.end_fill()
def carrelage(angle=60,taillecareaux=7,couleurcareaux="#ffffff",pourcentageécran=20):
    tortuecarrelage=Turtle(undobuffersize=0,visible=False,shape="square")
    tortuecarrelage.penup()
    gotopourcent(-100,0,tortuecarrelage)
    tortuecarrelage.setheading(angle)
    tortuecarrelage.fillcolor(couleurcareaux)
    gotopourcent(100,100,tortuecarrelage)
    tortuecarrelage.begin_fill()
    gotopourcent(100,0,tortuecarrelage)
    gotopourcent(0,0,tortuecarrelage)
    gotopourcent(0,pourcentageécran,tortuecarrelage)
    gotopourcent(100,pourcentageécran,tortuecarrelage)
    tortuecarrelage.end_fill()
    tortuecarrelage.pendown()
    tortuecarrelage.pencolor("#222222")
    k=-100
    while k<100:
        tortuecarrelage.forward(pourcentageécran/100*window_height()/sin(angle/360*2*pi))
        tortuecarrelage.forward(-pourcentageécran/100*window_height()/sin(angle/360*2*pi))
        k+=taillecareaux
        tortuecarrelage.penup()
        gotopourcent(k,0,tortuecarrelage)
        tortuecarrelage.pendown()
    k=pourcentageécran
    tortuecarrelage.penup()
    gotopourcent(0,0,tortuecarrelage)
    tortuecarrelage.begin_fill()
    while k>0:
        tortuecarrelage.penup()
        gotopourcent(0,k,tortuecarrelage)
        tortuecarrelage.pendown()
        gotopourcent(100,k,tortuecarrelage)
        k-=taillecareaux*cos(angle/360*2*pi)
    tortuecarrelage.setheading(0)
def afficherétagere(listequilles,quilles,manche,listetortuestempquilles,cadis1,cadis2):
    tracer(0)
    ht()
    up()
    setheading(0)
    tortueautre=Turtle(undobuffersize=0,visible=False,shape="square")
    tortueautre.setheading(0)
    tortueautre.ht()
    tortueautre.fillcolor("#ff9839")
    tortueautre.begin_fill()
    tortueautre.penup()
    gotopourcent(100,100,tortueautre)
    tortueautre.pendown()
    gotopourcent(100,0,tortueautre)
    gotopourcent(0,0,tortueautre)
    gotopourcent(0,100,tortueautre)
    gotopourcent(100,100,tortueautre)
    tortueautre.end_fill()
    carrelage()
    tailleetagere=1.2*window_height()/704
    taille2=3.1/tailleetagere*1.2/1366*window_width()
    etagere(tailleetagere,0,0,taille2,1,1,5,15,1.02)
    pancartecovid(0.6*window_height()/704,0,-240*window_height()/704)
    changerquilles(listequilles, quilles, manche, listetortuestempquilles)
    cadis1.turtlesize(window_width()/1366)
    cadis2.turtlesize(window_width()/1366)
    cadis1.st()
    cadis2.st()
    cadis1.setheading(90)
    cadis2.setheading(90)
    gotopourcent(80,30,cadis1)
    gotopourcent(20,30,cadis2)
def changerquilles(listequilles, quilles, manche, listetortuestempquilles):
        for i in range(3):
            for k in range(len(listequilles[i])):
                tortuetempquille=listetortuestempquilles[i][k]
                tortuetempquille.showturtle()
                tortuetempquille.turtlesize(0.8*window_width()/1366,0.8*window_width()/1366)
                tortuetempquille.penup()
                tortuetempquille.setheading(90)
                if (afficherquilles(quilles,len(listequilles[i]))[k]=="|" or i>manche) and not(i<manche):
                    tortuetempquille.goto((((k*4.75+15)*15/len(listequilles[i])+1)/100-0.5)*window_width(),((10*i+47)/100-0.5)*window_height())
                else:
                    stock(0.8*window_width()/1366,(((k*4.75+15)*15/len(listequilles[i])+1)/100-0.5)*window_width(),((10*i+47)/100-0.5)*window_height())
def nuage(ecran,x,y,scale=1,tortue=Turtle()):
    fait=True
    if not 'nuage' in ecran.getshapes():
        fait=False
        nuage = Shape("compound")
    tortue.penup()
    tortue.pencolor("#000000")
    tortue.fillcolor("#ffffff")
    gotopourcent(x,y,tortue)
    tortue.pendown()
    if not(fait):
        tortue.begin_poly()
    tortue.begin_fill()
    tortue.setheading(180)
    tortue.circle(-10*scale,90)
    tortue.circle(-30*scale,120)
    tortue.left(120)
    tortue.circle(-40*scale,180)
    tortue.left(120)
    tortue.circle(-30*scale,120)
    tortue.circle(-10*scale,90)
    gotopourcent(x,y,tortue)
    tortue.end_fill()
    if not(fait):
        tortue.end_poly()
        nuage.addcomponent(tortue.get_poly(),tortue.fillcolor(),tortue.pencolor())
        ecran.addshape('nuage', shape=nuage)
def lampe(x=0,y=0,tortuelampe=Turtle(undobuffersize=0,visible=False,shape="circle")):
    x2,y2=tortuelampe.pos()
    tortuelampe.penup()
    ymax=window_height()/2
    tortuelampe.goto(x,ymax)
    tortuelampe.begin_fill()
    tortuelampe.pencolor("#000000")
    tortuelampe.fillcolor("#dddddd")
    tortuelampe.pendown()
    tortuelampe.goto(x+3,ymax)
    tortuelampe.goto(x+3,y+50)
    tortuelampe.goto(x-3,y+50)
    tortuelampe.goto(x-3,ymax)
    tortuelampe.end_fill()
    tortuelampe.penup()
    tortuelampe.fillcolor("#f0f000")
    tortuelampe.goto(x-10,y+50)
    tortuelampe.pendown()
    tortuelampe.begin_fill()
    tortuelampe.goto(x+10,y+50)
    for y1 in range(y+50,y-50,-1):
        if y1>y:
            tortuelampe.goto(x+10+10*((y1-(y+50))/50)**2,y1)
        else:
            tortuelampe.goto(x+60-10*(((y-50)-y1)/50-1)**2,y1)
    tortuelampe.penup()
    tortuelampe.goto(x-10,y+50)
    tortuelampe.pendown()
    for y1 in range(y+50,y-50,-1):
        if y1>y:
            tortuelampe.goto(x-10-10*((y1-(y+50))/50)**2,y1)
        else:
            tortuelampe.goto(x-60+10*(((y-50)-y1)/50-1)**2,y1)
    for x1 in range(x-50,x+50):
        tortuelampe.goto(x1,4*((x1-x)/50)**2-52+y)
    tortuelampe.end_fill()
    tortuelampe.penup()
    tortuelampe.goto(x-20,(-20/15)**2-55+y)
    tortuelampe.pendown()
    tortuelampe.fillcolor("#eae59a")
    tortuelampe.begin_fill()
    for x1 in range(x-20,x+20):
        tortuelampe.goto(x1,4*((x1-x)/15)**2-58+y)
    tortuelampe.end_fill()
    tortuelampe.penup()
    tortuelampe.goto(x2,y2)
def fenetres(ecran,posnuagex):
    tortuefenetres=Turtle(undobuffersize=0,visible=False,shape="square")
    tortuefenetres.pencolor("#000000")
    tortuefenetres.penup()
    tortuefenetres.fillcolor("#00ffff")
    tortuefenetres.penup()
    gotopourcent(5,100,tortuefenetres)
    tortuefenetres.pendown()
    tortuefenetres.begin_fill()
    gotopourcent(95,100,tortuefenetres)
    gotopourcent(95,85,tortuefenetres)
    gotopourcent(5,85,tortuefenetres)
    gotopourcent(5,100,tortuefenetres)
    tortuefenetres.end_fill()
    tortuefenetres.penup()
    soleil(10,93,10,tortuefenetres)
    for k in range(150000):
        #tortuetempnuages=listetortuesnuages[k]
        k+=8
        nuage(ecran,(posnuagex*k/12+sin(k+7)*40)%70+10,sin(k+((posnuagex*k/12+sin(k+7)*40)//70)*37)*7+92,1/(2+0.5*sin(k)),tortuefenetres)

        #tortuetempnuages.turtlesize(1/(2+0.5*sin(k)),1/(2+0.5*sin(k)))
        #tortuetempnuages.penup()
        #gotopourcent((posnuagex*k/12+sin(k+7)*40)%70+10,sin(k+((posnuagex*k/12+sin(k+7)*40)//70)*37)*7+92,tortuetempnuages)
    tortuefenetres.fillcolor("#ff9839")
    for k in range(1,5):
        tortuefenetres.penup()
        gotopourcent(20*k-2.5,100,tortuefenetres)
        tortuefenetres.begin_fill()
        tortuefenetres.pendown()
        gotopourcent(20*k+2.5,100,tortuefenetres)
        gotopourcent(20*k+2.5,85,tortuefenetres)
        tortuefenetres.pencolor("#ff9839")
        gotopourcent(20*k-2.5,85,tortuefenetres)
        tortuefenetres.pencolor("black")
        gotopourcent(20*k-2.5,100,tortuefenetres)
        tortuefenetres.end_fill()
    for k in range(-2,3):
        lampe(k*200,int((0.37)*window_height()),tortuefenetres)
    update()
    tortuefenetres.setundobuffer(0)
    tortuefenetres.clear()
