from turtle import *

def logo(taille,x,y,tortuelogo):


    
    tortuelogo.up()
    tortuelogo.goto(x,y)
    tortuelogo.down()
    tortuelogo.pencolor('#872906')

    t=taille

    tracer(0)

    tortuelogo.up()
    tortuelogo.forward(t*60)
    tortuelogo.down()
    tortuelogo.left(50)
    tortuelogo.pencolor('black')
    tortuelogo.width(3*t)
    tortuelogo.forward(t*20)
    tortuelogo.backward(t*20)
    tortuelogo.right(85)
    tortuelogo.pencolor('#872906')
    tortuelogo.width(13*t)
    tortuelogo.circle(t*-110,205)
    tortuelogo.right(80)
    tortuelogo.pencolor('black')
    tortuelogo.width(3*t)
    tortuelogo.forward(t*20)
    tortuelogo.backward(t*40)
    tortuelogo.left(45)
    tortuelogo.forward(t*40)
    tortuelogo.right(45)
    tortuelogo.forward(t*-20)
    tortuelogo.forward(t*40)
    tortuelogo.forward(t*-15)
    tortuelogo.left(60)
    tortuelogo.pencolor('#872906')
    tortuelogo.width(13*t)
    tortuelogo.circle(t*-110,113)
    tortuelogo.left(55)
    tortuelogo.pencolor('black')
    tortuelogo.width(3*t)
    tortuelogo.forward(t*40)
    tortuelogo.forward(t*-50)
    tortuelogo.forward(t*30)
    tortuelogo.right(90)
    tortuelogo.forward(t*30)
    tortuelogo.left(90)
    tortuelogo.forward(t*-20)
    tortuelogo.up()
    tortuelogo.forward(t*160)
    tortuelogo.down()
    tortuelogo.right(96)
    tortuelogo.width(8*t)
    tortuelogo.left(180)
    tortuelogo.up()
    tortuelogo.circle(t*160,40)
    tortuelogo.down()
    r,k=tortuelogo.pos()
    tortuelogo.width(5*t)
    tortuelogo.pencolor('red')
    tortuelogo.right(90)
    tortuelogo.circle(t*90,20)
    tortuelogo.left(180)
    tortuelogo.circle(t*-90,40)
    tortuelogo.left(180)
    tortuelogo.circle(t*90,20)
    tortuelogo.left(90)
    tortuelogo.width(8*t)
    tortuelogo.left(175)
    for i in range (5):
        tortuelogo.circle(t*-198,21)
        a,b=tortuelogo.pos()
        tortuelogo.left(90)
        tortuelogo.forward(t*30)
        tortuelogo.left(90)
        tortuelogo.circle(t*-160,4)
        tortuelogo.left(180)
        tortuelogo.circle(t*160,8)
        tortuelogo.up()
        tortuelogo.goto(a,b)
        tortuelogo.down()
        tortuelogo.right(8)
        
        
    tortuelogo.left(40)
    tortuelogo.width(5*t)   
    tortuelogo.circle(t*-110,30)
    tortuelogo.left(180)
    tortuelogo.circle(t*110,42)
    tortuelogo.up()
    tortuelogo.goto(r,k)
    tortuelogo.left(70)
    tortuelogo.forward(t*27)
    tortuelogo.left(115)
    tortuelogo.pencolor('#872906')
    tortuelogo.down()
    tortuelogo.width(9*t)
    tortuelogo.circle(t*-50)
    tortuelogo.width(5*t)
    tortuelogo.right(87)
    tortuelogo.up()
    tortuelogo.pencolor('red')
    tortuelogo.forward(t*127)
    tortuelogo.down()
    tortuelogo.right(90)
    tortuelogo.circle(t*-90,20)
    tortuelogo.left(180)
    tortuelogo.circle(t*90,40)
    tortuelogo.left(180)
    tortuelogo.circle(t*-90,20)
    tortuelogo.right(73)
    tortuelogo.width(8*t)
    tortuelogo.left(175)
    for i in range (5):
        tortuelogo.circle(t*198,21)
        a,b=tortuelogo.pos()
        tortuelogo.right(90)
        tortuelogo.forward(t*30)
        tortuelogo.right(90)
        tortuelogo.circle(t*160,4)
        tortuelogo.left(180)
        tortuelogo.circle(t*-160,8)
        tortuelogo.up()
        tortuelogo.goto(a,b)
        tortuelogo.down()
        tortuelogo.left(8)
