from turtle import *
from ici import ici
from pan import pancarte

def pancartecovid(taille,x,y):

    tortuepancartecovid=Turtle(undobuffersize=0,visible=False,shape="square")

    tortuepancartecovid.up()
    tortuepancartecovid.goto(x,y)
    tortuepancartecovid.down()
    t=taille

    tracer(0)

    t=taille
    e=1.4
    a=1.8

    tortuepancartecovid.up()
    tortuepancartecovid.backward(t*12)
    tortuepancartecovid.right(90)
    tortuepancartecovid.forward(t*160)
    tortuepancartecovid.left(90)
    tortuepancartecovid.down()
    tortuepancartecovid.fillcolor('#8f5218')
    tortuepancartecovid.begin_fill()

    for i in range(2):
        tortuepancartecovid.forward(t*25)
        tortuepancartecovid.left(90)
        tortuepancartecovid.forward(t*320*e)
        tortuepancartecovid.left(90)

    tortuepancartecovid.left(90)
    tortuepancartecovid.forward(t*320*e)
    tortuepancartecovid.left(120)
    tortuepancartecovid.forward(t*12)
    tortuepancartecovid.left(60)
    tortuepancartecovid.forward(t*308*e)
    tortuepancartecovid.left(50)
    tortuepancartecovid.forward(t*12)
    tortuepancartecovid.end_fill()

    tortuepancartecovid.up()
    tortuepancartecovid.backward(t*190)
    tortuepancartecovid.left(45)
    tortuepancartecovid.forward(t*10)
    tortuepancartecovid.right(5)
    tortuepancartecovid.down()
    tortuepancartecovid.begin_fill()
    for i in range(2):
        tortuepancartecovid.forward(t*300)
        tortuepancartecovid.left(90)
        tortuepancartecovid.forward(t*160*a)
        tortuepancartecovid.left(90)
    tortuepancartecovid.end_fill()
    
    tortuepancartecovid.up()
    tortuepancartecovid.forward(t*150)
    tortuepancartecovid.left(90)
    tortuepancartecovid.forward(t*140)
    tortuepancartecovid.right(90)
    tortuepancartecovid.down()
    
    tail=0.5*t
    ta=tail
    g=1

    tracer(0)

    tortuepancartecovid.up()
    tortuepancartecovid.backward(ta*55)
    tortuepancartecovid.right(90)
    tortuepancartecovid.forward(ta*112)
    tortuepancartecovid.left(110)
    tortuepancartecovid.down()

    #T-Shirta eta cercle du logo
    tortuepancartecovid.begin_fill()
    tortuepancartecovid.forward(ta*30)
    tortuepancartecovid.right(110)
    tortuepancartecovid.circle(ta*25,160)
    tortuepancartecovid.right(90)
    tortuepancartecovid.forward(ta*27)
    tortuepancartecovid.right(120)
    tortuepancartecovid.width(g*3)
    tortuepancartecovid.circle(ta*-78,85)
    tortuepancartecovid.end_fill()
    tortuepancartecovid.circle(ta*-78,275)

    tortuepancartecovid.pencolor('blue')
    tortuepancartecovid.width(g*1)
    tortuepancartecovid.right(65)
    tortuepancartecovid.forward(ta*27)
    tortuepancartecovid.left(100)
    tortuepancartecovid.circle(ta*-25,160)
    tortuepancartecovid.left(100)
    tortuepancartecovid.forward(ta*30)
    tortuepancartecovid.backward(ta*30)
    
    #Visage du logo
    tortuepancartecovid.fillcolor('red')
    tortuepancartecovid.begin_fill()
    tortuepancartecovid.right(135)
    tortuepancartecovid.circle(ta*35,60)
    tortuepancartecovid.left(70)
    tortuepancartecovid.circle(ta*-5,90)
    tortuepancartecovid.forward(ta*15)
    tortuepancartecovid.circle(ta*-2,180)
    tortuepancartecovid.forward(ta*5)
    tortuepancartecovid.right(195)
    tortuepancartecovid.forward(ta*20)
    tortuepancartecovid.right(30)
    tortuepancartecovid.forward(ta*23)
    tortuepancartecovid.right(55)
    tortuepancartecovid.forward(ta*30)
    tortuepancartecovid.right(55)
    tortuepancartecovid.forward(ta*23)
    tortuepancartecovid.right(30)
    tortuepancartecovid.forward(ta*21)
    tortuepancartecovid.left(160)
    tortuepancartecovid.forward(ta*7)
    tortuepancartecovid.circle(ta*-2.5,180)
    tortuepancartecovid.forward(ta*17)
    tortuepancartecovid.circle(ta*-5,90)
    tortuepancartecovid.left(70)
    tortuepancartecovid.circle(ta*35,65)
    tortuepancartecovid.right(42)
    tortuepancartecovid.circle(ta*-25,160)
    tortuepancartecovid.end_fill()
    
    tortuepancartecovid.up()
    tortuepancartecovid.forward(ta*55)
    tortuepancartecovid.right(90)
    tortuepancartecovid.forward(ta*5)
    tortuepancartecovid.left(85)
    tortuepancartecovid.down()

    #Cheveux
    tortuepancartecovid.fillcolor('blue')
    tortuepancartecovid.begin_fill()
    tortuepancartecovid.circle(ta*-50,45)
    tortuepancartecovid.right(60)
    tortuepancartecovid.circle(ta*100,17)
    tortuepancartecovid.right(50)
    tortuepancartecovid.circle(ta*-50,45)
    tortuepancartecovid.left(140)
    tortuepancartecovid.circle(ta*35,90)
    tortuepancartecovid.circle(ta*-20,20)
    tortuepancartecovid.circle(ta*20,20)
    tortuepancartecovid.left(20)
    tortuepancartecovid.circle(ta*40,140)
    tortuepancartecovid.end_fill()

    #Masque
    tortuepancartecovid.left(60)
    tortuepancartecovid.up()
    tortuepancartecovid.forward(ta*10)
    tortuepancartecovid.down()
    tortuepancartecovid.begin_fill()
    tortuepancartecovid.left(15)
    tortuepancartecovid.circle(ta*-80,35)
    tortuepancartecovid.right(80)
    tortuepancartecovid.forward(ta*25)
    tortuepancartecovid.circle(ta*-22,150)
    tortuepancartecovid.right(20)
    tortuepancartecovid.forward(ta*28)
    tortuepancartecovid.end_fill()
    
    tortuepancartecovid.up()
    tortuepancartecovid.forward(ta*120)
    tortuepancartecovid.left(90)
    tortuepancartecovid.forward(ta*145)
    tortuepancartecovid.right(90)
    tortuepancartecovid.write("EST OBLIGATOIRE", font=("Arial", int(28*ta), "normal"))
    tortuepancartecovid.backward(ta*5)
    tortuepancartecovid.right(90)
    tortuepancartecovid.down()
    tortuepancartecovid.width(g*4)
    tortuepancartecovid.forward(ta*215)
    tortuepancartecovid.right(110)
    tortuepancartecovid.forward(ta*30)
    tortuepancartecovid.left(150)
    tortuepancartecovid.forward(ta*40)
    tortuepancartecovid.right(40)
    tortuepancartecovid.forward(ta*80)

    tortuepancartecovid.up()
    tortuepancartecovid.backward(ta*290)
    tortuepancartecovid.left(90)
    tortuepancartecovid.forward(ta*60)
    tortuepancartecovid.down()
    tortuepancartecovid.width(g*1)
    tortuepancartecovid.write("ICI,LE MASQUE", font=("Arial", int(28*ta), "normal"))
    tortuepancartecovid.up()
    tortuepancartecovid.forward(ta*60)
    tortuepancartecovid.right(90)
    tortuepancartecovid.forward(ta*86)
    tortuepancartecovid.down()
    tortuepancartecovid.fillcolor('black')
    tortuepancartecovid.begin_fill()
    for i in range(2):
        tortuepancartecovid.forward(ta*110)
        tortuepancartecovid.left(90)
        tortuepancartecovid.forward(ta*35)
        tortuepancartecovid.left(90)
    tortuepancartecovid.end_fill()
    tortuepancartecovid.up()
    tortuepancartecovid.forward(ta*20)
    tortuepancartecovid.left(90)
    tortuepancartecovid.forward(ta*5)
    tortuepancartecovid.down()
    tortuepancartecovid.pencolor('white')
    tortuepancartecovid.write("COVID-19", font=("Arial", int(13*ta), "bold"))
    
    tortuepancartecovid.up()
    tortuepancartecovid.backward(ta*370)
    tortuepancartecovid.right(90)
    tortuepancartecovid.backward(ta*15)
    tortuepancartecovid.pencolor('blue')
    tortuepancartecovid.write("Ensemble,", font=("Arial", int(16*ta), "normal"))
    tortuepancartecovid.backward(ta*110)
    tortuepancartecovid.right(90)
    tortuepancartecovid.forward(ta*25)
    tortuepancartecovid.write("faisons bloc contre le coronavirus", font=("Arial", int(16*ta), "normal"))
    tortuepancartecovid.forward(ta*40)
    tortuepancartecovid.left(90)
    tortuepancartecovid.backward(ta*95)
    tortuepancartecovid.down()

    tortuepancartecovid.width(g*3)

    for i in range(2):
        tortuepancartecovid.forward(ta*510)
        tortuepancartecovid.left(90)
        tortuepancartecovid.forward(ta*500)
        tortuepancartecovid.left(90)
    update()


