from setup import *
def bonbon(taille,x,y,angle=0):
    y+=20*taille
    tortuebonbon=Turtle(undobuffersize=0,visible=False,shape="square")
    setup(x,y,angle,tortuebonbon)

    t=taille/8
    tortuebonbon.width(3*t)

    tracer(0)
    
    tortuebonbon.up()
    tortuebonbon.forward(t*100)
    tortuebonbon.left(90)
    tortuebonbon.forward(t*-20)

    tortuebonbon.down()

    for i in range(4):

        ed,rf=tortuebonbon.pos()
    
        tortuebonbon.dot(120*t,'green')
        tortuebonbon.right(30)
        tortuebonbon.up()
        tortuebonbon.forward(t*60)
        tortuebonbon.down()
        tortuebonbon.left(90)
        tortuebonbon.circle(t*60)

        tortuebonbon.fillcolor('black')
        tortuebonbon.begin_fill()
        tortuebonbon.left(90)
        tortuebonbon.circle(t*100,62)
        tortuebonbon.right(90)
        tortuebonbon.circle(t*-60,40)
        tortuebonbon.right(45)
        tortuebonbon.circle(t*-100,72)
        tortuebonbon.right(45)
        tortuebonbon.circle(t*-60,40)
        tortuebonbon.end_fill()

        tortuebonbon.up()
        tortuebonbon.left(180)
        tortuebonbon.circle(t*-60,5)
        tortuebonbon.down()
        
        tortuebonbon.pencolor('blue')
        tortuebonbon.fillcolor('red')
        tortuebonbon.begin_fill()
        tortuebonbon.circle(t*-5,80)
        tortuebonbon.circle(t*-70,20)
        tortuebonbon.circle(t*70,20)
        tortuebonbon.circle(t*7,70)
        tortuebonbon.right(150)
        tortuebonbon.circle(t*-30,50)
        tortuebonbon.left(80)
        tortuebonbon.circle(t*-30,50)
        tortuebonbon.right(70)
        tortuebonbon.forward(t*10)
        tortuebonbon.left(90)
        tortuebonbon.circle(t*-35,65)
        tortuebonbon.right(70)
        tortuebonbon.forward(t*10)
        tortuebonbon.left(90)
        tortuebonbon.circle(t*-35,45)
        tortuebonbon.right(70)
        tortuebonbon.forward(t*20)
        tortuebonbon.circle(t*30,40)
        tortuebonbon.circle(t*-30,30)
        tortuebonbon.right(107)
        tortuebonbon.circle(t*60,63)
        tortuebonbon.end_fill()

        tortuebonbon.up()
        tortuebonbon.circle(t*60,125)
        tortuebonbon.left(185)
        tortuebonbon.down()

        tortuebonbon.begin_fill()
        tortuebonbon.circle(t*5,80)
        tortuebonbon.circle(t*70,20)
        tortuebonbon.circle(t*-70,20)
        tortuebonbon.circle(t*-7,70)
        tortuebonbon.left(150)
        tortuebonbon.circle(t*30,50)
        tortuebonbon.right(80)
        tortuebonbon.circle(t*30,50)
        tortuebonbon.left(70)
        tortuebonbon.forward(t*10)
        tortuebonbon.right(90)
        tortuebonbon.circle(t*35,65)
        tortuebonbon.left(70)
        tortuebonbon.forward(t*10)
        tortuebonbon.right(90)
        tortuebonbon.circle(t*35,45)
        tortuebonbon.left(70)
        tortuebonbon.forward(t*20)
        tortuebonbon.circle(t*-30,40)
        tortuebonbon.circle(t*30,30)
        tortuebonbon.left(107)
        tortuebonbon.circle(t*-60,63)
        tortuebonbon.end_fill()

        tortuebonbon.up()
        tortuebonbon.goto(ed,rf)
        tortuebonbon.circle(t*150,90)
        tortuebonbon.down()

    update()

