from setup import *
from ovale import ovalerelatif
from troudé import trou
def dé(ecran,taille,x,y,angle=0):
    de = Shape("compound")

    tortuede=Turtle(undobuffersize=0,visible=False,shape="square")
    setup(x,y,angle,tortuede)

    t=taille/10

    tracer(0)

    tortuede.up()
    tortuede.forward(t*75)
    tortuede.right(90)
    tortuede.forward(t*130)
    tortuede.left(90)
    tortuede.down()

    tortuede.width(1*t)
    tortuede.pencolor('black')
    tortuede.fillcolor('black')
    tortuede.begin_poly()
    tortuede.right(6)
    tortuede.circle(t*1400,11.5)
    tortuede.circle(t*5,100)
    tortuede.left(10)
    tortuede.circle(t*115,22)
    tortuede.left(124)
    tortuede.circle(t*-20,90)
    tortuede.left(8.5)
    tortuede.forward(t*239)
    tortuede.left(90)
    tortuede.forward(t*25)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.begin_poly()
    tortuede.circle(t*-20,65)
    tortuede.right(2.5)
    tortuede.forward(t*200)
    tortuede.circle(t*-55,58)
    tortuede.left(11)
    tortuede.forward(t*175)
    tortuede.left(60)
    tortuede.circle(t*7,100)
    tortuede.left(10.5)
    tortuede.forward(t*160)
    tortuede.circle(t*90,72)
    tortuede.right(17)
    tortuede.forward(t*206)
    tortuede.circle(t*20,100)
    tortuede.forward(t*15)
    tortuede.left(70)
    tortuede.forward(t*27)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.fillcolor('white')
    tortuede.begin_poly()
    tortuede.width(4*t)
    tortuede.right(101)
    tortuede.forward(t*240)
    tortuede.circle(t*40,80)
    tortuede.right(15)
    for i in range(154):
        tortuede.width(t*(3.2+0.02*i))
        tortuede.forward(t*1)
    
    tortuede.circle(t*45,55)
    tortuede.right(11)
    tortuede.forward(t*210)
    tortuede.circle(t*20,74)
    for i in range(239):
        tortuede.width(t*(6.08-0.01*i))
        tortuede.forward(t*1)
    tortuede.width(3*t)
    tortuede.circle(t*50,60)
    tortuede.forward(t*40)
    (k,l)=tortuede.pos()
    tortuede.forward(t*110)
    tortuede.circle(t*60,50)
    tortuede.forward(t*205)
    tortuede.circle(t*26,60)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.right(110)
    tortuede.up()
    tortuede.goto(k,l)
    tortuede.backward(5*t)
    tortuede.left(90)
    tortuede.forward(t*255)
    tortuede.right(46)
    tortuede.down()
    angle=[0,141,116]
    trait=[229,168,255]
    for i in range (3):
        tortuede.left(angle[i])
        (a,b)=tortuede.pos()
        for j in range(trait[i]):
            tortuede.width(t*(10-0.03*j))
            tortuede.forward(t*1)
        tortuede.goto(a,b)
        
    tortuede.up()
    tortuede.backward(84*t)
    tortuede.left(90)
    tortuede.forward(t*210)
    tortuede.down()
    tortuede.begin_poly()
    tortuede.width(t*5)
    tortuede.left(75)
    tortuede.pencolor('black')
    tortuede.forward(t*105)
    tortuede.circle(t*-20,78)
    tortuede.forward(t*250)
    tortuede.width(t*8)
    tortuede.circle(t*-18,83)
    tortuede.forward(t*120)
    r,c=tortuede.pos()
    tortuede.circle(t*-100,14)
    for i in range (210):
        tortuede.width(t*(8-0.035*i))
        tortuede.forward(t*1)
    
    tortuede.circle(t*-20,85)
    tortuede.forward(t*246)
    tortuede.right(89)
    tortuede.forward(t*223)
    tortuede.left(15)
    tortuede.circle(t*43,70)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())   
    tortuede.up()
    tortuede.left(100)
    tortuede.goto(r,c)
    
    tortuede.down()
    tortuede.width(6*t)
    tortuede.circle(t*-10,95)
    for i in range (260):
        tortuede.width(t*(6-0.015*i))
        tortuede.forward(t*1)

    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.up()
    tortuede.forward(t*45)
    tortuede.left(90)
    tortuede.forward(t*75)
    tortuede.down()
    tortuede.begin_poly()
    trou(tortuede,90,0.95*t)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.up()
    tortuede.forward(t*-170)
    tortuede.right(90)
    tortuede.forward(t*15)
    tortuede.down()
    tortuede.begin_poly()
    trou(tortuede,80,0.95*t)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.up()
    tortuede.left(120)
    tortuede.forward(t*140)
    tortuede.down()
    tortuede.begin_poly()
    trou(tortuede,90,0.95*t)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.up()
    tortuede.forward(t*165)
    tortuede.down()
    tortuede.begin_poly()
    trou(tortuede,90,0.95*t)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.up()
    tortuede.left(57)
    tortuede.forward(t*-105)
    tortuede.down()
    tortuede.begin_poly()
    trou(tortuede,90,0.95*t)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.up()
    tortuede.left(90)
    tortuede.forward(t*260)
    tortuede.down()
    tortuede.begin_poly()
    trou(tortuede,-70,0.95*t)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.up()
    tortuede.right(20)
    tortuede.forward(t*-200)
    tortuede.down()
    tortuede.left(90)
    tortuede.begin_poly()
    trou(tortuede,180,0.95*t)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.up()
    tortuede.left(5)
    tortuede.forward(t*-130)
    tortuede.down()
    tortuede.begin_poly()
    trou(tortuede,180,0.95*t)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.up()
    tortuede.left(5)
    tortuede.forward(t*-120)
    tortuede.down()
    tortuede.begin_poly()
    trou(tortuede,180,0.95*t)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.up()
    tortuede.left(17)
    tortuede.forward(t*-240)
    tortuede.down()
    tortuede.begin_poly()
    trou(tortuede,180,0.95*t)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.up()
    tortuede.left(120)
    tortuede.forward(t*170)
    tortuede.down()
    tortuede.begin_poly()
    trou(tortuede,0,0.95*t)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.up()
    tortuede.left(38)
    tortuede.forward(t*-125)
    tortuede.down()
    tortuede.begin_poly()
    trou(tortuede,0,0.95*t)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())

    tortuede.up()
    tortuede.left(42)
    tortuede.forward(t*-120)
    tortuede.down()
    tortuede.begin_poly()
    trou(tortuede,0,0.95*t)
    tortuede.end_poly()
    de.addcomponent(tortuede.get_poly(),tortuede.fillcolor(),tortuede.pencolor())
    ecran.addshape('de', shape=de)
