from setup import *
def baguette(taille,x,y,angle=0):

    tortuebaguette=Turtle(undobuffersize=0,visible=False,shape="square")
    setup(x,y,angle,tortuebaguette)
    t=taille/10

    tracer(0)
    tortuebaguette.up()
    tortuebaguette.backward(t*17)
    tortuebaguette.right(51)
    tortuebaguette.down()

    tortuebaguette.pencolor('#b99e5d')
    tortuebaguette.fillcolor('#f9d877')
    tortuebaguette.begin_fill()
    tortuebaguette.width(4*t)
    qs,wx=tortuebaguette.pos()
    tortuebaguette.forward(t*100)
    tortuebaguette.circle(t*35,180)
    tortuebaguette.right(5)
    tortuebaguette.circle(t*2650,7.35)
    tortuebaguette.circle(t*23,180)
    tortuebaguette.right(21)
    tortuebaguette.circle(t*650,22)
    tortuebaguette.end_fill()

    tortuebaguette.up()
    tortuebaguette.forward(t*100)
    tortuebaguette.circle(t*35,180)
    tortuebaguette.down()
    
    tortuebaguette.right(7)
    for i in range(3):
        tortuebaguette.up()
        tortuebaguette.circle(t*2650,2.45)
        tortuebaguette.down()
        sd,cv=tortuebaguette.pos()
        tortuebaguette.left(150)
        tortuebaguette.up()
        tortuebaguette.forward(t*20)
        tortuebaguette.down()
        tortuebaguette.width(3*t)
        tortuebaguette.forward(t*60)
        tortuebaguette.up()
        tortuebaguette.right(130)
        tortuebaguette.forward(t*20)
        tortuebaguette.down()
        tortuebaguette.right(65)
        tortuebaguette.forward(t*40)
        tortuebaguette.up()
        tortuebaguette.goto(sd,cv)
        tortuebaguette.left(45)
        tortuebaguette.down()
        tortuebaguette.width(4*t)

    tortuebaguette.up()
    tortuebaguette.goto(qs,wx)
    tortuebaguette.left(90)
    tortuebaguette.forward(t*90)
    tortuebaguette.right(90)
    tortuebaguette.right(170)
    tortuebaguette.down()

    tortuebaguette.begin_fill()
    tortuebaguette.width(4*t)
    qs,wx=tortuebaguette.pos()
    tortuebaguette.forward(t*100)
    tortuebaguette.circle(t*35,180)
    tortuebaguette.right(5)
    tortuebaguette.circle(t*2650,7.35)
    tortuebaguette.circle(t*23,180)
    tortuebaguette.right(21)
    tortuebaguette.circle(t*650,22)
    tortuebaguette.end_fill()

    tortuebaguette.up()
    tortuebaguette.forward(t*100)
    tortuebaguette.circle(t*35,180)
    tortuebaguette.down()
    
    tortuebaguette.right(7)
    for i in range(3):
        tortuebaguette.up()
        tortuebaguette.circle(t*2650,2.45)
        tortuebaguette.down()
        sd,cv=tortuebaguette.pos()
        tortuebaguette.left(150)
        tortuebaguette.up()
        tortuebaguette.forward(t*20)
        tortuebaguette.down()
        tortuebaguette.width(3*t)
        tortuebaguette.forward(t*60)
        tortuebaguette.up()
        tortuebaguette.right(130)
        tortuebaguette.forward(t*20)
        tortuebaguette.down()
        tortuebaguette.right(65)
        tortuebaguette.forward(t*40)
        tortuebaguette.up()
        tortuebaguette.goto(sd,cv)
        tortuebaguette.left(45)
        tortuebaguette.down()
        tortuebaguette.width(4*t)

    tortuebaguette.up()
    tortuebaguette.goto(qs,wx)
    tortuebaguette.backward(t*80)
    tortuebaguette.right(115)
    
    tortuebaguette.down()

    tortuebaguette.fillcolor('#f8d998')
    tortuebaguette.pencolor('#4e3b30')
    tortuebaguette.begin_fill()
    tortuebaguette.width(5*t)
    tortuebaguette.circle(t*600,19)
    tortuebaguette.right(125)
    tortuebaguette.circle(t*450,27)
    tortuebaguette.circle(t*-10,80)
    tortuebaguette.circle(t*-200,50)
    tortuebaguette.right(55)
    tortuebaguette.circle(t*450,25)
    tortuebaguette.right(132)
    tortuebaguette.circle(t*600,4.5)
    tortuebaguette.end_fill()

    tortuebaguette.fillcolor('#b2834b')
    
    tortuebaguette.begin_fill()
    tortuebaguette.left(180)
    tortuebaguette.circle(t*600,4.5)
    tortuebaguette.right(150)
    tortuebaguette.circle(t*600,3.7)
    tortuebaguette.right(100)
    tortuebaguette.up()
    tortuebaguette.forward(t*20)
    tortuebaguette.end_fill()

    tortuebaguette.left(75)
    tortuebaguette.forward(t*150)
    tortuebaguette.left(90)
    tortuebaguette.forward(t*20)
    tortuebaguette.right(110)
    tortuebaguette.down()
    tortuebaguette.begin_fill()
    tortuebaguette.circle(t*600,5.5)
    tortuebaguette.right(160)
    tortuebaguette.circle(t*600,5.5)
    tortuebaguette.right(100)
    tortuebaguette.up()
    tortuebaguette.forward(t*20)
    tortuebaguette.end_fill()
    
    ht()

    update()
