from setup import *
def coca(ecran,taille,x,y,angle=0):
    x+=5*taille
    tortuecoca=Turtle(undobuffersize=0,visible=False,shape="square")
    coca = Shape("compound")

    setup(x,y,angle,tortuecoca)

    t=taille/9

    tracer(0)

    tortuecoca.up()
    tortuecoca.forward(t*54)

    tortuecoca.left(90)
    tortuecoca.forward(t*14)
    tortuecoca.down()
    tortuecoca.right(90)

    #Bouteille en verre
    tortuecoca.fillcolor('#9fccf6')
    tortuecoca.pencolor('#9fccf6')
    tortuecoca.begin_poly()
    tortuecoca.forward(t*6)
    tortuecoca.right(100)
    tortuecoca.circle(t*-300,8)
    tortuecoca.circle(t*140,40)
    tortuecoca.right(3)
    tortuecoca.circle(t*-300,10)
    tortuecoca.right(5)
    tortuecoca.circle(t*-500,5.9)
    tortuecoca.circle(t*-20,78)
    tortuecoca.left(6)
    tortuecoca.circle(t*-230,34)
    tortuecoca.circle(t*-20,78)
    tortuecoca.right(2.5)
    tortuecoca.circle(t*500,5.9)
    tortuecoca.right(5)
    tortuecoca.circle(t*-300,10)
    tortuecoca.right(5)
    tortuecoca.circle(t*140,40)
    tortuecoca.right(2)
    tortuecoca.circle(t*-300,7)
    tortuecoca.right(101)
    tortuecoca.left(110)
    tortuecoca.circle(t*-100,37)
    tortuecoca.left(5)
    tortuecoca.circle(t*-200,20)
    tortuecoca.left(5)
    tortuecoca.circle(t*150,31)
    tortuecoca.right(91)
    tortuecoca.forward(t*55)
    tortuecoca.right(91)
    tortuecoca.circle(t*150,31)
    tortuecoca.left(0)
    tortuecoca.circle(t*-200,20)
    tortuecoca.left(3)
    tortuecoca.circle(t*-100,37)
    tortuecoca.end_poly()
    coca.addcomponent(tortuecoca.get_poly(),tortuecoca.fillcolor(),tortuecoca.pencolor())

    #Coca en liquide
    tortuecoca.width(1*t)
    tortuecoca.left(13)
    tortuecoca.up()
    tortuecoca.left(90)
    tortuecoca.forward(t*-5)
    tortuecoca.right(90)
    tortuecoca.down()
    tortuecoca.pencolor('#030b1a')
    tortuecoca.fillcolor('#030b1a')
    tortuecoca.begin_poly()
    tortuecoca.circle(t*-300,10)
    tortuecoca.circle(t*100,40)
    tortuecoca.circle(t*-300,10)
    tortuecoca.right(5)
    tortuecoca.circle(t*-500,5.9)
    tortuecoca.circle(t*-20,78)
    tortuecoca.left(3)
    tortuecoca.circle(t*-200,32)
    tortuecoca.circle(t*-20,78)
    tortuecoca.right(3)
    tortuecoca.circle(t*500,5.9)
    tortuecoca.right(5)
    tortuecoca.circle(t*-300,10)
    tortuecoca.circle(t*100,40)
    tortuecoca.right(2)
    tortuecoca.circle(t*-300,9)
    tortuecoca.circle(t*-100,43)
    tortuecoca.right(57)
    tortuecoca.forward(t*113)
    tortuecoca.right(63)
    tortuecoca.circle(t*-100,43)
    tortuecoca.end_poly()
    coca.addcomponent(tortuecoca.get_poly(),tortuecoca.fillcolor(),tortuecoca.pencolor())

    tortuecoca.up()
    tortuecoca.left(177)
    tortuecoca.right(94)
    tortuecoca.forward(t*11.5)
    tortuecoca.left(94)
    
    #Etiquette rouge 
    tortuecoca.fillcolor('#ab0000')
    tortuecoca.begin_poly()
    tortuecoca.circle(t*100,37)
    tortuecoca.left(71)
    tortuecoca.forward(t*150)
    tortuecoca.left(71)
    tortuecoca.circle(t*100,37)
    tortuecoca.left(73)
    tortuecoca.forward(t*150)
    tortuecoca.end_poly()
    coca.addcomponent(tortuecoca.get_poly(),tortuecoca.fillcolor(),tortuecoca.pencolor())


    tortuecoca.up()
    tortuecoca.backward(t*40)
    tortuecoca.left(90)
    tortuecoca.forward(t*10)
    tortuecoca.down()

    #Etiquette avec l'inscription coca
    tortuecoca.fillcolor('#cdd0d5')
    tortuecoca.begin_poly()
    tortuecoca.right(90)
    tortuecoca.circle(t*15,180)
    tortuecoca.forward(t*85)
    tortuecoca.circle(t*15,180)
    tortuecoca.forward(t*85)
    tortuecoca.end_poly()
    coca.addcomponent(tortuecoca.get_poly(),tortuecoca.fillcolor(),tortuecoca.pencolor())

    tortuecoca.up()
    tortuecoca.backward(t*85)
    tortuecoca.down()
    tortuecoca.write('COCA', font=("Arial", int(t*20), "normal"))
    
    tortuecoca.up()
    tortuecoca.forward(t*10)
    tortuecoca.right(90)
    tortuecoca.forward(t*30)
    tortuecoca.down()

    #Bulle de coca
    tortuecoca.pencolor('#cdd0d5')
    tortuecoca.dot(t*10)

    tortuecoca.up()
    tortuecoca.forward(t*10)
    tortuecoca.right(90)
    tortuecoca.forward(t*-30)
    tortuecoca.down()

    tortuecoca.dot(t*25)

    tortuecoca.up()
    tortuecoca.forward(t*10)
    tortuecoca.right(90)
    tortuecoca.forward(t*-30)
    tortuecoca.down()

    tortuecoca.dot(t*10)

    tortuecoca.up()
    tortuecoca.right(90)
    tortuecoca.forward(t*30)
    tortuecoca.down()

    tortuecoca.dot(t*15)

    tortuecoca.up()
    tortuecoca.left(50)
    tortuecoca.forward(t*30)
    tortuecoca.down()

    tortuecoca.dot(t*12)

    tortuecoca.up()
    tortuecoca.left(39)
    tortuecoca.pencolor('#ab0000')
    tortuecoca.forward(t*240)
    tortuecoca.down()

    #Bouchon rouge
    tortuecoca.fillcolor('#ab0000')
    tortuecoca.begin_poly()
    tortuecoca.right(80)
    tortuecoca.circle(t*15,170)
    tortuecoca.forward(t*45)
    tortuecoca.circle(t*15,180)
    tortuecoca.forward(t*50)
    tortuecoca.end_poly()
    coca.addcomponent(tortuecoca.get_poly(),tortuecoca.fillcolor(),tortuecoca.pencolor())
    ecran.addshape('coca', shape=coca)
