from turtle import *

def wumpus(taille,x,y):
    
    up()
    goto(x,y)
    down()


    t=taille

    tracer(0)

    width(3*t)
    up()
    backward(t*88)
    left(90)
    forward(t*12)
    left(90)
    down()

    #Corps du wumpus
    fillcolor('#90a1e7')
    begin_fill()
    forward(t*30)
    circle(t*47,90)
    forward(t*112)
    circle(t*14,180)
    forward(t*24)
    right(90)
    forward(t*56)
    right(90)
    forward(t*23)
    circle(t*14,180)
    forward(t*23)
    right(90)
    backward(t*30)
    forward(t*83)
    left(180)
    circle(t*-14,90)
    forward(t*40)
    up()
    forward(t*40)
    end_fill()

    up()
    left(180)
    fillcolor('#abbaf1')
    #Pelage avant
    begin_fill()
    forward(t*80)
    circle(t*13,90)
    right(90)
    down()
    forward(t*25)
    circle(t*14,180)
    forward(t*25)
    right(90)
    forward(t*37)
    right(90)
    forward(t*25)
    circle(t*14,180)
    forward(t*25)
    right(90)
    circle(t*20,90)
    forward(t*60)
    up()
    forward(t*20)
    down()
    end_fill()

    up()
    backward(t*22)
    down()

    #Contour de la tête
    begin_fill()
    right(90)
    forward(t*20)
    circle(t*44,90)
    forward(t*13)
    up()
    forward(t*83)
    down()
    circle(t*44,90)
    forward(t*142)
    circle(t*44,65)
    up()
    circle(t*44,25)
    forward(t*66)
    down()
    forward(t*30)
    circle(t*44,90)
    forward(t*142)
    end_fill()

    up()
    circle(t*44,90)
    forward(t*96)
    circle(t*44,90)
    forward(t*142)
    down()

    #Arrière de la tête
    fillcolor('#90a1e7')
    begin_fill()
    forward(t*30)
    circle(t*44,65)
    up()
    circle(t*44,25)
    forward(t*66)
    down()
    forward(t*30)
    circle(t*44,90)
    forward(t*30)
    up()
    left(180)
    circle(t*-44,90)
    forward(t*96)
    circle(t*-44,90)
    end_fill()

    #Oeil
    forward(t*35)
    right(90)
    forward(t*80)
    down()
    dot(25*t)

    up()
    backward(t*53)
    right(90)
    forward(t*62)
    down()

    #Oreille
    fillcolor('#abbaf1')
    begin_fill()
    forward(t*50)
    circle(t*30,90)
    forward(t*20)
    circle(t*30,90)
    forward(t*50)
    end_fill()

    up()
    left(90)
    forward(t*66)
    left(90)
    down()

    #Interieur de l'oreille
    fillcolor('#90a1e7')
    begin_fill()
    forward(t*50)
    circle(t*15,90)
    forward(t*25)
    circle(t*15,90)
    forward(t*30)
    up()
    forward(t*20)
    down()
    end_fill()
    
    up()
    forward(t*135)
    left(90)
    forward(t*50)
    right(90)
    down()

    #Contour museau
    fillcolor('#c9d5f1')
    begin_fill()
    forward(t*80)
    circle(t*-20,90)
    forward(t*30)
    circle(t*-35,90)
    forward(t*50)
    circle(t*-35,90)
    forward(t*30)
    circle(t*-20,90)
    end_fill()

    #Relief de son museau
    fillcolor('#b4c8f4')
    begin_fill()
    left(180)
    forward(t*20)
    circle(t*20,90)
    forward(t*30)
    circle(t*35,90)
    forward(t*20)
    left(180)
    circle(t*-35,90)
    forward(t*30)
    circle(t*-20,90)
    end_fill()

    up()
    forward(t*16)
    right(90)
    forward(t*50)
    left(90)
    down()

    #Trou de narine
    fillcolor('#a8b7ed')
    begin_fill()
    forward(t*23)
    circle(t*-8,180)
    forward(t*23)
    circle(t*-8,180)
    end_fill()

    up()
    forward(t*50)
    down()

    begin_fill()
    forward(t*10)
    circle(t*-8,180)
    forward(t*10)
    circle(t*-8,180)
    end_fill()

    up()   
    backward(t*40)
    right(90)
    forward(t*54)
    left(90)
    down()
    forward(t*30)
    
    up()
    backward(t*334)
    left(90)
    forward(t*12)
    down()

    #Queue
    fillcolor('#abbaf1')
    begin_fill()
    left(10)
    forward(t*30)
    circle(t*24,250)
    forward(t*33)
    end_fill()

    
    update()

